### ISSUE TITLE
New Error on HomeBridge Boot

### ISSUE THREAD

**Issue by sdevo619** [chrisjshull/homebridge-nest#217] opened 2020-02-28 01:15 UTC
This error only began to happen after the most recent home bridge-nest update. Using a Google Account. Here is the error. I already tried reauthorizing by following the steps on the your site, but cannot get rid of this error. Please help. Also, thank you for making this to begin with!!!

![image](https://user-images.githubusercontent.com/7008354/75501369-bd9d9e00-5984-11ea-8331-eff374d39b46.png)

**Comment by adriancable** [comment] 2020-02-28 01:53
@sdevo619 - there is one pinned issue for this project, and it is a duplicate of your issue - #209. Please review the pinned issue, as we don't need a duplicate issue. Thanks!

**Closed by adriancable** 2020-02-28 01:53 UTC
