### ISSUE TITLE
Error: Stream closed with error code NGHTTP2_INTERNAL_ERROR

### ISSUE THREAD

**Issue by vzlgdu** [chrisjshull/homebridge-nest#493] opened 2022-01-11 06:36 UTC
Sometimes I receive the following error:

gen 11 00:10:03 homebridgea homebridge[5559]: [11/1/2022, 00:10:03] [Nest] API observe: error Error: Stream closed with error code NGHTTP2_INTERNAL_ERROR
gen 11 00:10:03 homebridgea homebridge[5559]:     at new NodeError (node:internal/errors:371:5)
gen 11 00:10:03 homebridgea homebridge[5559]:     at ClientHttp2Stream._destroy (node:internal/http2/core:2313:13)
gen 11 00:10:03 homebridgea homebridge[5559]:     at _destroy (node:internal/streams/destroy:102:25)
gen 11 00:10:03 homebridgea homebridge[5559]:     at ClientHttp2Stream.destroy (node:internal/streams/destroy:64:5)
gen 11 00:10:03 homebridgea homebridge[5559]:     at Http2Stream.onStreamClose (node:internal/http2/core:545:12) {
gen 11 00:10:03 homebridgea homebridge[5559]:   code: 'ERR_HTTP2_STREAM_ERROR'
gen 11 00:10:03 homebridgea homebridge[5559]: }
gen 11 00:10:03 homebridgea homebridge[5559]: [11/1/2022, 00:10:03] [Nest] Retrying in 10 seconds

The environment is:

RPI4
HB 1.3.9

Can you help me?

Thanks

**Comment by Nastras** [comment] 2022-01-19 17:21
Same 4 me.

**Comment by adriancable** [comment] 2022-01-19 18:29
@Nastras - what exactly is "the same for you"? Do you just find the messages ugly, or do you actually have a functional issue with the plug in?

**Comment by Nastras** [comment] 2022-01-19 18:42
Hey @adriancable,

I also get the message very often. Unfortunately, I do not know what this exactly says or what the problem is.

The plugin says Retrying in 10 seconds. But nothing happens, the message remains in the log. Very often I get a message in Homekit that the smoke detectors are not available until I restart the instance.

I am not sure if it is related to this but last week all Nest Protect devices disappeared from Homekit. Shortly after that they were added as new. Of course, all automations were broken as a result.

I haven't made any changes to the Nest hardware or your plugin in a long time. It has actually been working very well so far. 

![E90F7283-11A9-48FD-896F-5862A73CB45B](https://user-images.githubusercontent.com/27686185/150193926-adb3ecc9-734f-426d-90cc-6aea065500e3.jpeg)

**Comment by adriancable** [comment] 2022-01-19 19:01
@Nastras - this message is completely normal. It does not indicate there is a problem. If you have other issues, this message will not give any insight because it is normal.

If you have a message in HomeKit saying that the smoke detectors are not available, please provide a screenshot of that message so we can debug that.

If Homebridge devices disappear from HomeKit, it means that you have lost the contents of the ~/.homebridge/persist folder. You will need to debug why this may happen because I do not have any information on where and how you are running Homebridge. Examples of how it may happen: unclean shutdown of the machine prevents pending writes to this folder from being flushed (e.g. pulling the power cord out). Or you are using a Docker container which starts in a 'virgin' state when restarted.

**Comment by Nastras** [comment] 2022-01-19 19:17
If you say that the message is not an error then it is good. I just find it very irritating that the plugin says retrying in 10 seconds but nothing happens.

It then looks as if the plugin has hung up. At least if you only have nest protect 😅

I am running homebridge on a pi 4. each plugin has its own instance.
Why the persist file has deleted itself was understandable for me. There was nothing apparent in the log. I could only imagine that it was an error during the automatic nightly reboot of the pi.

**Comment by adriancable** [comment] 2022-01-19 19:22
@Nastras - what do you mean when you say "nothing happens"? The plug-in retries its call to the Nest service in 10 seconds (as it is advising), and if that call succeeds, then naturally it doesn't print another error. Surely since the alternative is getting another error, the fact that "nothing happens" is a good thing?

**Comment by Nastras** [comment] 2022-01-19 19:32
I mean that the log does not show that the retrying of the nest api was successful after 10 seconds.

Since I only have the Nest Protect is a status change that is displayed in the log only rarely. 

That's why I always have this red error message as the last status in the log.

If the plugin would show in the log that it has successfully sent a new request to the api it would be more understandable for the user.

**Comment by Nastras** [comment] 2022-01-19 19:38
I think that the log can also be very helpful for the user to identify errors. Not only for the developer 😉

Without log I would be completely lost at homebridge 😅😅😅

**Comment by jom** [comment] 2022-01-27 11:36
I am also experiencing this issue. I see this in the log and then after that point the state for my Nest devices stops updating. I assume this is with all devices, but the only one I monitor the state of is the thermostat. The devices still show up, but they don't get updates for the heating state or target temperature (for example).

**Comment by adriancable** [comment] 2022-01-28 21:17
Fixed in 4.6.4, now released.

**Closed by adriancable** 2022-01-28 21:17 UTC
