### ISSUE TITLE
Add the Ability to set Fan Switch longer than 15 minutes and Fahrenheit temperature in the logs?

### ISSUE THREAD

**Issue by thehauntedmattress** [chrisjshull/homebridge-nest#100] opened 2019-07-20 21:46 UTC
First off a big thank you for updating this plug-in so that we would not be affected by the developer shut down.  My first question is by doing this, will we no longer have to worry about the nest developer API (or whatever it is) blocking us if we change the temperature too much within a set period of time?

My next questions are two feature requests: 

Would it be possible for when turning on the fan switch to be able to set one of the fan times that the Nest offers other than 15 minutes (eg. 30 minutes, 45 minutes, 1 hour, 2 hours, 4 hours, 8 hours, or 12 hours?)

Also would it be possible to have the temperature in the logs of homebridge-config-ui-x show up as Fahrenheit instead of Celsius?

Thank you for your continued work and development on this project!

**Comment by adriancable** [comment] 2019-07-21 02:12
Hi – your question about API throttling is a good one. I am not 100% sure but I believe things are better now and possibly completely fixed. I have not seen the rate throttle kicking in with the new code but please let me know if it happens to you.

 

Regarding your feature requests:

 
Control of how long the fan runs – yes absolutely. I’ll add this as a setting in the config.json in the next release of the plug-in.
Temperatures in the logs in Fahrenheit – HomeKit uses Celcius internally but I can add a setting in the config to translate the temps to Fahrenheit for the logs. But can you tell me why specifically this would be useful for you? i.e. what are you using the messages in the logs for?
 

-Adrian

**Comment by thehauntedmattress** [comment] 2019-07-21 02:18
Sometimes when I am using homebridge-config-ui-x I like to see the logs process a command, and it is hard for me to decipher if the thermostat is being set to the correct temperature if it is in Celsius.

My last question to you (which I had forgotten to ask about before) is sometimes when I have a homekit automation change a temperature, the thermostat will set itself to something else.  For example, I have it so that when I leave home, my thermostat is supposed to set itself to 78F (this is via a homekit automation), but for some reason it often sets itself to 68F.  I was wondering if there was a fix for this?  Thanks.

**Comment by adriancable** [comment] 2019-07-21 02:26
That's interesting. Does that happen even with version 3.0.0 of the plug-in?

Can you capture what happens in the homebridge logs when this occurs?

**Comment by thehauntedmattress** [comment] 2019-07-21 02:35
With my initial testing with 3.0.0, it seems that the automations flash the thermostat to 68F for a second or two before setting itself to the desired temperature.

**Comment by adriancable** [comment] 2019-07-21 02:39
Can you send me what you see in the Homebridge log output on the console when this happens? Thanks!

**Comment by thehauntedmattress** [comment] 2019-07-21 02:45
So I just ran an automatoin that is supposed to set the thermostat to 78F.  But instead, the thermostat flashed to 68F and then finally set itself to 75F.  Here is the log.


[2019-7-20 22:43:17] [Nest] Queuing to set heating threshold temperature 20
[2019-7-20 22:43:17] [Nest] Queuing to set temperature 25.6
[2019-7-20 22:43:17] [Nest] Queuing to set cooling threshold temperature 24
[2019-7-20 22:43:17] [Nest] Setting target fan state for Nest Thermostat to: false
[2019-7-20 22:43:22] [Nest] Heating threshold temperature set to 20 null
[2019-7-20 22:43:22] [Nest] Temperature set to 25.6 null
[2019-7-20 22:43:22] [Nest] Cooling threshold temperature set to 24 null

**Comment by thehauntedmattress** [comment] 2019-07-21 02:47
Based on what I am capturing, it seems that it is trying to set the heat threshold even though I have the automation set to only cool.  So I see that it went to 68F, then 78F, and then back down to 75F

**Comment by adriancable** [comment] 2019-07-21 04:30
I can reproduce this. The plug-in shouldn't be setting the heating or cooling threshold like this. Unfortunately at least on my end there seems to be something wrong with the Nest service right now. Even just using the real Nest app, changes I make don't update the thermostat, which keeps flicking online/offline. Is yours also having this issue?

Will see if it's back in action tomorrow. In the mean time please email me at: adrian.cable@gmail.com - I will get you some code to try to hopefully fix this.

**Comment by KozzakO** [comment] 2019-07-21 11:00
I just noticed this issue too. When I set Nest target temperature in HomeKit, say, from 20 to 22C, the setting gets updated in the Nest app and in the thermostat. However, the temperature setting goes back to 20C in HomeKit after a few seconds.

**Comment by thehauntedmattress** [comment] 2019-07-21 17:49
I don't see online/offline but I ran an automation this morning and the same issue happened again.

**Comment by mjgunn99** [comment] 2019-07-22 02:17
I've been experiencing some weird behavior since yesterday as well.  My thermostat is always set to Cool mode.  I was on the old version of the plugin, and noticed last night that when Eco mode was turned off by the switch (done by an automation when I get home) the thermostat is being set to auto mode instead of Cool. 

Tonight I saw there was a new version of the plugin (thanks for the awesome update btw), so I installed it but the behavior is still the same.  In addition to changing the mode, Eco on/off is acting funny. I'll turn Eco on in the home app and it will turn off immediately, but it will show Eco mode in the Nest app and at the thermostat.  Checking the homebridge log I do see Eco quickly going on and then off, I guess it's happening fast enough that Nest is ignoring the second command and that's why Eco actually does get turned on?

Sorry if I shouldn't be posting in this thread about this, but some of my issues (specifically the mode changing) seem to be similar.

**Comment by adriancable** [comment] 2019-07-22 05:36
All - a lot of fixes in the latest commit which may address some or all of these things. Please can you try to see how it works with setting the temperature by automation (thehauntedmattress), and also eco mode (mjgunn99). Let me know if it works better for you.

**Comment by thehauntedmattress** [comment] 2019-07-22 12:18
@adriancable 

So I guess since this isn't technically a new version, Homebrige-config-ui-x did not see it as an update.  I typically update homebridge packages using it for simplicity.  However, because of this, I manually ran "sudo npm install -g homebridge-nest" to see if it would update.  

I tried using `"fanDurationMinutes":` 480 to see if the fan would stay on for 8 hours.  When I tested it, the thermostat said it would only be on for 15 minutes still.  So unless I did something incorrect, that feature did not work.  If I want it set for 8 hours I do put `"fanDurationMinutes":` 480 and not `"fanDurationMinutes":` 8 correct?

**Comment by adriancable** [comment] 2019-07-22 13:18
Using npm to update wouldn't get you the new version. It hasn't been published on npm yet, since I am still testing new features. To get it, pull from the git repository. Then try the fanDurationMinutes feature again.

**Comment by mjgunn99** [comment] 2019-07-22 13:33
Just installed the new version, still not working but acting differently.  When I flip eco on, it will stay on eco briefly and stay that way for a few seconds before the switch turning itself off. When I check the nest app right away it will show as being in Eco mode, but within about 30 seconds the nest's mode will be turned to off. 

So the change from the last version is that instead of the nest being bumped out of Eco mode in to Auto mode, it's being bumped out in to Off mode.

**Comment by adriancable** [comment] 2019-07-22 13:39
I've just fixed one bug in the eco mode code. I'm not sure if this will fix your issue, but please pull from the repo and give it a try, and let me know how you get on. If it doesn't work, please email me the debug output from Homebridge to adrian.cable@gmail.com and I'll see if I can figure it out.

One question. Before going to eco mode, what mode was your thermostat in?

**Comment by mjgunn99** [comment] 2019-07-22 13:52
My thermostat lives in Cool mode year round (FL heat), and great news it looks like the bug is squashed with the new version.  Eco mode is going on and staying there when I flip the switch on, and coming out of it correctly back in to Cool mode (the only mode I ever keep it on, FL heat) when I turn it off. Thank you for the quick fix.

How come this started happening with the older version 2.3.x (4 I think?) the other night with the old token login after working for so long?  Did Nest change something recently?

**Comment by adriancable** [comment] 2019-07-22 14:03
I honestly don't know. It's possible they changed something. I only got my first Nest device 5 days ago so not familiar with any previous changes to the API. Glad it works for you now.

**Comment by mjgunn99** [comment] 2019-07-22 14:03
Actually things are still a little off.  My main problem is fixed, Eco is working correctly.  When I'm out of Eco mode I've been adjusting the temperature up and down and checking the nest app and all my changes are being made instantly just as they should be so that's working correctly. 

However the Home app doesn't seem to have updated the temperature inside the house in awhile, so while the Nest app reports it being 76 inside the house, the home app is displaying it as still being 75.  Also, when the Nest is in Eco mode, instead of the home app reflecting the eco range of temps like it usually does, right now it's just saying "cool to 75". However in the Nest app things are displaying correctly, the system is in Eco mode and the AC is not running.

**Comment by adriancable** [comment] 2019-07-22 14:10
(1) Regarding Nest app reporting 76 F but the home app displaying 75 F. HomeKit handles temperatures in deg C internally and then converts to deg F if needed. The Nest app does its own conversion. I have observed that the two round differently occasionally so they may be a degree off. Please can you watch it and let me know if there is ever more than 1 deg F difference between the two.

(2) Regarding Home app in Eco mode, the problem is that HomeKit doesn't natively recognise such a thing as Eco mode. As far as HomeKit is concerned, the thermostat is still in cool mode, since this is what it reports even when Eco mode is switched on. If you think this would be better, I can make it so that instead of saying "cool to 75" it reports as "off". Let me know.

**Comment by mjgunn99** [comment] 2019-07-22 14:27
Thanks for the explanation on the temps, I'll check in during the day and see if it ever drifts more than 1 degree apart. Won't be long with the hot weather today before I'll know.

So if I'm understanding right, right now it's reporting cooling to 75 because the temp inside is 75, and as the temp rises through the day it will report cooling to 76, 77, etc?  If the option is that vs displaying as off I would probably vote for off. 

However I could be wrong, because I honestly don't normally look at the home app nearly as much as I have been in the last day or two while I've been troubleshooting this, but I could have sworn that when the themostat was in Eco mode it used to display the Eco range of temperatures in the Home app. Pure guessing, couldn't that be achieved by displaying it as being in "Auto" mode with the heat to temp being the low end of Eco, and the cool to temp being the high end of Eco? If that's even doable? Of course I could just be crazy and it never actually did display like that.

**Comment by adriancable** [comment] 2019-07-22 15:15
Eco mode works differently depending on whether your system is set to 'heat' or 'cool' only, or whether it's set to 'heat-cool' (which HomeKit calls Auto). If it's set to 'cool' only, the Home app will report 'Cooling to X' in Eco mode, where X is the eco temperature threshold set on the device (X is not the actual ambient temperature). This matches the position of the 'notch' in the Nest app.

If the thermostat is set to 'heat-cool' and Eco mode is on, then the Home app will report a range of temperatures, which again match the position of the notches in the Nest app.

The behaviour you're reporting where it seems to say 'cooling to X' in Eco mode where X is the current ambient temperature doesn't sound right. Can you send me a side-by-side screenshot of the Nest app and the Home app? And, also the console output from Homebridge would be helpful.

**Comment by adriancable** [comment] 2019-07-22 16:47
@thehauntedmattress - can you try setting the temperature via automation with the latest version of the plug-in on github, and see if that now works properly? Thanks!

**Comment by thehauntedmattress** [comment] 2019-07-22 17:23
Will have to do when I get home.

**Comment by thehauntedmattress** [comment] 2019-07-22 22:52
@adriancable so I just want to be sure I'm doing this right before I overwrite some files...I just downloaded it from the Git repository.  Where do I copy the files?  Is it the /usr/lib/node_modules folder?

**Comment by adriancable** [comment] 2019-07-22 23:01
The files go in /usr/local/lib/node_modules/homebridge-nest … the homebridge-nest subfolder might already be in the ZIP file you downloaded from Github (if you got the files that way) in which case you just extract into /usr/local/lib/node_modules.

**Comment by thehauntedmattress** [comment] 2019-07-22 23:16
I don't have a directory on my pi that is /usr/local/lib/node_modules

**Comment by adriancable** [comment] 2019-07-22 23:21
Do: npm get prefix

 

Then look in that path, with lib/node_modules stuck on the end. You should find homebridge-nest in there.

 

-Adrian

**Comment by thehauntedmattress** [comment] 2019-07-22 23:37
So I moved the new Homebridge-nest folder there and I keep getting an exit code when Homebridge attempts to start up.

**Comment by adriancable** [comment] 2019-07-22 23:44
I recommend you find the existing homebridge-nest folder (look for nest-connection.js, then go up one level) and then drop the new files in there.

**Comment by thehauntedmattress** [comment] 2019-07-22 23:55
I got it.  Currently testing now.

**Comment by thehauntedmattress** [comment] 2019-07-23 00:30
Everything seems to be working.  The automations fired correctly without jumping to another temperature first.  The fan setting works also.

**Comment by toshibochan** [comment] 2019-07-23 01:28
Look in /usr/lib/node_modules/

**Comment by thehauntedmattress** [comment] 2019-07-23 01:30
I got it working thank you.

**Comment by adriancable** [comment] 2019-07-23 02:19
OK great!

**Comment by thehauntedmattress** [comment] 2019-07-23 02:20
I will keep an eye on this throughout the week but thank you so much for your work on this!

**Closed by adriancable** 2019-07-23 02:19 UTC
