### ISSUE TITLE
24 degrees bug

### ISSUE THREAD

**Issue by tomeranaray** [chrisjshull/homebridge-nest#81] opened 2019-02-08 06:10 UTC
When setting the temperature in the Home app, the Nest thermostat ignores the value and sets the thermostat to 24 degrees Celsius. 

**To Reproduce**
1.  Set the thermostat. I have seen this behaviour with a HomeKit Automation but also when manually requesting a thermostat change. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version latest 
homebridge --version latest
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by ratsoid** [comment] 2019-02-17 13:11
Same thing is happening to me... The darn 24' bug

**Comment by tomster11** [comment] 2019-02-17 19:00
Same problem here... Docker installation on a Synology. node v10.14.1, homebridge v0.4.45

When e temp is set in a scene it almost always goes to 24 degrees Celsius...

**Comment by jsstelt** [comment] 2019-02-20 18:45
Same problem here. 
I'm using a scene for "good night" had two days in a row that the temp goes to 24 degrees at night.

**Comment by CaptBeard** [comment] 2019-03-01 23:03
I'm also having this issue. Seems to only occur when changing the temperature via a scene. Mine goes to 76ºF (the one true ambient temperature unit 😃)

**Comment by dcac** [comment] 2019-03-06 12:13
Same here - although the initiation of it seems fairly random (for instance, it just started now, and there was no inciting scene to cause it).

It also happens quite often around 3:30-4am.

**Comment by tastheimer** [comment] 2019-03-18 13:21
I also have been encountering this issue. Though in my case from the logs it looks like it attempted to set my cooling setting to 24, yet it set my heating temp to 24 instead.

**Comment by aveach** [comment] 2019-04-04 16:41
I filed this a few days ago which I guess is a dupe. 

https://github.com/chrisjshull/homebridge-nest/issues/88

Doesn't look like @chrisjshull maintains this anymore so if/when I have a chance I can try to debug this and cut a fork. If anyone has any more logging than what I gathered, please send it my way.

**Comment by chrisjshull** [comment] 2019-04-04 17:21
I’m here, I just have a full time job. Please submit a PR :) 

~Chris

**Comment by magefesa** [comment] 2019-04-07 18:16
Would be great if someone could solve this error... the other stuff is perfect with my Homekit / Alexa Ecosystem

**Comment by jeffmarcilliat** [comment] 2019-04-10 04:24
Is anyone already working on a PR? I woke up this morning in a sweat. :)

**Comment by aveach** [comment] 2019-04-10 16:27
> Is anyone already working on a PR? I woke up this morning in a sweat. :)

I'd like to but I just haven't had the time to debug the cause yet.

**Comment by magefesa** [comment] 2019-04-10 16:52
Don t worry!!!
Thanks for your great efforts and work !!

Frank

--

**Comment by aveach** [comment] 2019-04-10 18:38
After quickly looking at things... 

I'm almost certain the issue is in the debounce call: 
```javascript
NestThermostatAccessory.prototype.setCoolingThresholdTemperatureDebounced = debounce(function (temperature, callback) {
  const target = this.device.temperature_scale === 'F' ? 'target_temperature_high_f' : 'target_temperature_high_c';
  switch (this.device.hvac_mode) {
    case 'heat-cool':
      return Promise.resolve()
        .then(this.updateDevicePropertyAsync.bind(this, target, temperature, 'cooling threshold temperature'))
        .asCallback(callback);
    default:
      this.log.debug('Mode is set to ' + this.device.hvac_mode + ', unable to set cooling threshold temperature');
      break;
  }
}, 5000);
```
@chrisjshull looks like we are using `4.0.8` and current lodash.debounce is now at `4.17.11` should we update the dependency? (not sure it will solve it, but could help)

Also, a bit weird... I see `Queuing to set cooling threshold temperature 24.4` in the Homebridge logs but I can't find the string `Queuing to set` at all in the entire project. So curious that that print is even happening. 

Besides that, looks like the debounce only has one switch case `heat-cool`. Shouldn't we expand this to have switch cases for all the `hvac_modes`?

**Comment by aveach** [comment] 2019-04-11 02:39
Also, testing a bit here at home. Looks like this jump only happens when you are setting the heat from eco mode. If you change the setting to heat first, then set the temp, the jump doesn’t happen.

**Comment by jeffmarcilliat** [comment] 2019-04-11 04:51
Thanks @aveach for isolating the issue! So as a workaround, if I turn off Eco Mode during the same scene that I update my desired temperature, that might work? There is no way to dictate the order in which the accessories update in the Home app.

**Comment by aveach** [comment] 2019-04-11 05:05
@jeffmarcilliat I did try adding the “eco switch off” to the scene once but that failed to execute (I was already in heat mode so I suspect that’s why) but you’re right, you can’t dictate the order that things are executed. 

The work around I mentioned was just done manually. (e.g. long press on the thermostat icon, tap mode, switch to heat, tap Temp, then set the temp to 70). 

I’ll definitely look into this more very soon though.

**Comment by magefesa** [comment] 2019-04-11 06:37
Thank you !!

Frank

--

**Comment by aveach** [comment] 2019-04-18 17:18
I worked on this a bit yesterday. The issues are most definitely in `NestThermostatAccessory.prototype.setTargetTemperatureDebounced`
 
Basic Issues:
1. We don't properly set an updated `hvac_mode` because sometimes we don't fall into the correct `if` statement based on our value in `mode = this.device.hvac_mode`. 
2. When we do update the `hvac_mode` most of the time it does not actually apply in time before we try to set the temperature. 
3. Sometimes the Nest API returns a "Blocked" message that does not allow us to control the thermostat for some reason (need to read through the Nest API)

Action items:
- Be sure we correctly update the `hvac_mode` and wait till its full applied
- Re write the logic in `setTargetTemperatureDebounced`
- [File a bug with Apple](https://developer.apple.com/bug-reporting) to add a delay feature and order of operations to HomeKit scenes and automation flows (I encourage everyone to do this)
- Figure out why Nest API sometimes returns a "Blocked" message

I have already rewritten some of the logic in `setTargetTemperatureDebounced` and things seem to be better. A few more tweaks and we should be there. I also exposed a "Heat Mode" switch. This could be used in the future if/when HomeKit supports delays (e.g. Turn on Heat Mode switch, wait 5 seconds, then set heat to `x`)

**Comment by chrisjshull** [comment] 2019-04-18 20:26
one option might be to buffer all incoming changes for a brief window (200ms?) and then reconcile them in a sane order.

and on #3, "Blocked" usually means that you hit the API rate limit from Nest. it's a PITA, but goes away in about an hour IIRC

**Comment by magefesa** [comment] 2019-04-19 07:32
Come on ! You re near ! 
Thanks for keep on !

**Comment by aveach** [comment] 2019-04-19 16:41
> one option might be to buffer all incoming changes for a brief window (200ms?) and then reconcile them in a sane order.
> 
> and on #3, "Blocked" usually means that you hit the API rate limit from Nest. it's a PITA, but goes away in about an hour IIRC

Thanks for the reply @chrisjshull. Looks like one way to get around the blocked message is to test on the [Nest Home Simulator](https://developers.nest.com/guides/home-simulator) so I'll try to get that going. 

Also, I added a bunch of log lines here and there and it looks like we are calling getCooling and getHeating Threshold  fair amount, could be leading to what's causing us to hit the API rate limit so quickly.

**Comment by chrisjshull** [comment] 2019-04-19 17:05
If you get the sim working, please submit a PR with instructions in the readme. Would be super helpful!

**Comment by jeffmarcilliat** [comment] 2019-04-25 16:51
This does not just happen when a scene is changing from Eco Mode or Off. I hit the bug again yesterday when just having a scene adjust temperature up while already in heating mode.

**Comment by adriancable** [comment] 2019-07-23 02:22
Please can you try the latest commit and see if this is now fixed.

**Comment by adriancable** [comment] 2019-07-26 23:04
Closing for now. Believe fixed.

**Closed by adriancable** 2019-07-26 23:04 UTC
