### ISSUE TITLE
Eco mode temperature gets adjusted

### ISSUE THREAD

**Issue by stephendowning** [chrisjshull/homebridge-nest#171] opened 2019-11-04 19:56 UTC
Whenever I've left the house and my Nest goes to auto away mode I cannot adjust the temperature in Homekit without first turning eco mode off manually. If I don't do that then it sets the eco mode temperature to the chosen temp and I end up with my heating never turning off.

It never used to do this so something has changed and this behaviour is very much not desirable!

**Comment by adriancable** [comment] 2019-11-06 20:59
@stephendowning - thanks for your note. This is intentional behaviour and in fact was a common request, so that the eco bands could be set from HomeKit.

It isn't clear what behaviour would you like to see when you manually adjust the temperature while in eco mode. Imagine you have a cool + heat HVAC system, you're in eco mode, and you ask Siri to set the temperature to 70 degrees. At that point, not clear whether (for example) you are asking it to cool or heat. Thoughts?

-Adrian

**Comment by stephendowning** [comment] 2019-11-06 21:01
Hi Adrian this behaviour has changed at some point.

If I adjust the temperature while in auto away eco mode I would expect HomeKit to behave like the Nest app does and either prompt me to drop out of eco mode or automatically drop me out of eco mode. My post on reddit has received replies from others stating they don't like this behaviour either and I wonder if you could please consider allowing it to be customisable? I'm based in the UK so only use my Nest for heating.

**Comment by adriancable** [comment] 2019-11-06 21:04
@stephendowning - the plug-in was rewritten at 3.0.0 so any similarities with, or differences to, previous behaviour are what they are.

I'm happy to work on adding an option to configure this behaviour, since I do understand your reasons for it. But I need to define the precise behaviour. If your thermostat is heat-only then yes I can flip out of eco mode, into heat mode, with your specified temperature. But I need to implement logic that works for all HVAC system types, and in much of the world full HVAC is the most common. What do you think the behaviour should be if I command Siri to set a temperature while in Eco mode, and the thermostat supports heating and cooling?

**Comment by stephendowning** [comment] 2019-11-06 21:06
So if I had an HVAC system and I asked it to set a temp that was outside of the eco range I would expect it in an ideal world to prompt me and say that is above or below your eco range do you wish to heat or cool. If that weren't possible then I'd want it to automatically drop out of eco mode.

As a starting point could you add a configuration option just for heating - I'm happy to test as required?

**Comment by adriancable** [comment] 2019-11-06 21:08
Thanks - I can test it locally. I'll add this to the list of things to put in the next release. Probably what I will do: if you have a heat/cool system and you ask for a temperature that's less than the ambient, it cools, otherwise it heats.

**Comment by stephendowning** [comment] 2019-11-06 21:09
Amazing thanks so much - do you have any idea when this might be available?

**Comment by adriancable** [comment] 2019-11-06 21:10
I have a new version of the plug-in pretty much ready to go, which has a bunch of new stuff including full support for cameras and doorbells. Unfortunately it needs an update to Homebridge to work. From the Homebridge github I understand that is in progress, but I don't have an ETA - as soon as that's ready I'll release. I'm pretty sure I'll be able to get the eco mode option in for that.

**Comment by stephendowning** [comment] 2019-11-06 21:10
That's great thanks!

**Comment by adriancable** [comment] 2019-11-06 21:40
@stephendowning - I have some code for you to test. Email me at adrian.cable@gmail.com if interested.

**Comment by neilmorton** [comment] 2019-11-18 13:12
@stephendowning & @adriancable Great to hear that this has been raised and is being addressed. I too have just experienced this, or something similar.

I wanted to just run it by both of you for any thoughts you may have if I may?

Scenario: UK based, heating only.
Nest thermostat is set up with auto away mode, so after a period of time it switches over to eco. Eco is set to 9C, basically the heating won't come on when not in the property unless it gets pretty cold.
I created a Homekit scene 'Heat Home' with the idea of turning off Eco mode & setting the temperature to a higher one so that when I know I will be home in 20 - 30 minutes I can say 'Hey Siri, Heat Home'.
The issue is that whilst this does increase the temperature, this too increases the eco temperature (i.e. the active setting), and not the 'normal' temperature as per my just switching off the eco mode.

It is very possible that your change will fix this, but wanted to bring it to your attention so that you can test (or I can if you want to send me the code).

Thanks.

**Comment by adriancable** [comment] 2019-11-18 19:49
@neilmorton - this should have been addressed by the fix I did for @stephendowning. If you send me an email at adrian.cable@gmail.com I can get you some code to test.

**Comment by neilmorton** [comment] 2019-11-20 14:52
@adriancable - I can confirm that the test code resolves this issue for me. Thank you for the great work.

**Comment by marcbush** [comment] 2020-02-13 06:14
Hello. I am also experience this issue too. I’ve emailed above email. 

Im in UK, and whenever the temperature is changed in HomeKit it is altering the eco temperature! We often set the heating then let the house cool down naturally via eco mode, but this is being overrode and the heating just stays on constantly. 😞

Will this update be pushed to production soon? Or has it already and it’s a config update?

Thank you!

**Comment by neilmorton** [comment] 2020-02-13 10:37
@marcbush, the last release [3.5.1](https://github.com/chrisjshull/homebridge-nest/releases/tag/v3.5.1) was on 27th August 2019. 

@adriancable was really helpful in sending me some updated code which solved the issue for me.

As far as I am aware the change does need a source code update, so hopefully @adriancable will get back to you.

**Comment by adriancable** [comment] 2020-02-18 17:18
Fixed in 4.4.0, now released.

**Closed by adriancable** 2020-02-18 17:18 UTC

**Comment by marcbush** [comment] 2020-02-19 17:48
Thank you 🙏
