### ISSUE TITLE
Plugin error message

### ISSUE THREAD

**Issue by angyp** [chrisjshull/homebridge-nest#409] opened 2021-06-02 23:24 UTC
This doesn't affect my operation but I would like to clean it up if possible. I understand the message however how do I change the threshold on my thermostat if it's not wired for cooling at all?

[6/3/2021, 9:17:27 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 9.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[6/3/2021, 9:17:27 AM] [homebridge-nest] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at NestThermostatAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:76:27)
    at CoolingThresholdTemperature.emit (events.js:316:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CoolingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at CoolingThresholdTemperature.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at CoolingThresholdTemperature.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1216:10)

**Comment by adriancable** [comment] 2021-06-03 01:02
This is a duplicate of several other closed issues (#384, #376 etc.). It's a quirk of the fact that Nest applies different temperature limits to safety temperatures as to user settable temperatures. HomeKit however can't support different temperature limits at different times.

But it doesn't matter. These warnings are for developers, not for users, so you can ignore them.

**Closed by adriancable** 2021-06-03 01:02 UTC
