### ISSUE TITLE
Unable to Link Account

### ISSUE THREAD

**Issue by gferguson1815** [chrisjshull/homebridge-nest#461] opened 2021-11-05 17:03 UTC
After installing and trying to link my Nest account (Google Account) the image is blank

**To Reproduce**
1. Click 'Link Account'
2. Presented with screen saying that a one time access code will be required
3. Click login
4. Blank white window displayed

**Expected behavior**

Ability to log into the Nest account to link

Include with your bug report this version info:

node --14.18.1
homebridge --1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment] 2021-11-05 17:09
May I kindly request that you check if issues are already posted before duplicating? That is the route to a much faster resolution.

This is a duplicate of #452 and #458 and furthermore is a HOOBS issue and isn’t an issue with this plug-in.

**Closed by adriancable** 2021-11-05 17:09 UTC
