### ISSUE TITLE
Nest disappear from HomeKit app

### ISSUE THREAD

**Issue by toshibochan** [chrisjshull/homebridge-nest#198] opened 2020-01-07 15:49 UTC
I mean still using old user name and password version of Nest in today nest just disappear from HomeKit app. 
[1/7/2020, 7:47:53 AM] [Nest] Auth failed: Nest rejected the account email/password specified in your Homebridge configuration file. Please check
[1/7/2020, 7:47:53 AM] [Nest] Unable to connect to Nest service.
Nest is stopping support older developers loving?

**Comment by adriancable** [comment] 2020-01-07 15:59
@toshibochan - this is a duplicate of #195 - please read there for details and a workaround.

**Closed by adriancable** 2020-01-07 15:59 UTC

**Comment by toshibochan** [comment] 2020-01-07 21:03
That’s mean have to migrate to google account?

**Comment by toshibochan** [comment] 2020-01-08 00:19
Thank you I migrated to google account and now working great!

**Comment by jeffmarcilliat** [comment] 2020-01-11 19:42
@toshibochan How did you migrate and update your config.json?

**Comment by toshibochan** [comment] 2020-01-11 19:54
I just fallow the instruction.

Open a Chrome browser tab in Incognito Mode (or clear your cache).
Open Developer Tools (View/Developer/Developer Tools).
Click on 'Network' tab. Make sure 'Preserve Log' is checked.
In the 'Filter' box, enter issueToken
Go to home.nest.com, and click 'Sign in with Google'. Log into your account.
One network call (beginning with iframerpc) will appear in the Dev Tools window. Click on it.
In the Headers tab, under General, copy the entire Request URL (beginning with https://accounts.google.com, ending with nest.com). This is your "issueToken" in config.json.
In the 'Filter' box, enter oauth2/iframe
Several network calls will appear in the Dev Tools window. Click on the last iframe call.
In the Headers tab, under Request Headers, copy the entire cookie (beginning OCAK=... - include the whole string which is several lines long and has many field/value pairs - do not include the cookie: name). This is your "cookies" in config.json.
In the 'Filter' box, enter issue_jwt
Click on the last issue_jwt call.
In the Headers tab, under Request Headers, copy the entire x-goog-api-key (do not include the x-goog-api-key: name). This is your "apiKey" in config.json.

**Comment by toshibochan** [comment] 2020-01-11 19:56
https://www.google.com/amp/s/staceyoniot.com/google-nest-home-account-migration-it-shouldnt-be-this-hard/amp/

**Comment by toshibochan** [comment] 2020-01-11 22:31
"platforms": [{
                "platform": "Nest",
                "googleAuth": {
                        "issueToken": "https://accounts.google.com.......”,
                        "cookies": "OCAK=guzqaO....”,
                        "apiKey": "AIzaSyAdkSI.......”
                }
        }, {

**Comment by mriksman** [comment] 2020-01-20 13:52
I've successfully migrated to googleAuth. But the Nest items still aren't appearing in Home...?

```
[1/20/2020, 1:50:44 PM] [Nest] initing thermostat "Guest": deviceId: 02AA01AC0615098N structureId: 0de15b80-015c-11e5-9cdc-22000b1e805f
[1/20/2020, 1:50:44 PM] [Nest] Initializing platform accessory 'Guest'...
```
