### ISSUE TITLE
Nest API call to subscribe to device settings updates returned an error: undefined

### ISSUE THREAD

**Issue by Garywoo** [chrisjshull/homebridge-nest#157] opened 2019-09-27 20:39 UTC
Getting this error on startup:
`Nest API call to subscribe to device settings updates returned an error: undefined` then `Retrying in 40 seconds.` which then repeats. 

This error appears to be preventing Homebridge from finishing its initialisation, and actually begin running. 

Config:
```
        {
            "platform": "Nest",
            "email": "my@email.com",
            "password": "password",
            "structureId": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        }
```
I have multiple structures on my Nest account. I have not linked my Nest account with Google.

Would appreciate some guidance.

**Comment by adriancable** [comment] 2019-10-02 19:56
@Garywoo - have you tried deleting the "structureId" line from your config.json and seeing if that works?

If not - please add:

"options": [ "Debug.Verbose" ],

to your config, then run: homebridge -D

Then please post the output of that. Thanks!

**Comment by Garywoo** [comment] 2019-10-02 21:04
@adriancable I just tested removing the "structureId" line, but the same issue persisted.

Here's the (hopefully) relevant output after adding the line '`"options": [ "Debug.Verbose" ]` to the homebridge-nest object in my config, and running homebridge -D.
```
0|homebridge  | [10/2/2019, 8:53:38 PM] Loaded plugin: homebridge-alexa
0|homebridge  | [10/2/2019, 8:53:38 PM] Registering platform 'homebridge-alexa.Alexa'
0|homebridge  | [10/2/2019, 8:53:38 PM] ---
0|homebridge  | [10/2/2019, 8:53:38 PM] Loaded plugin: homebridge-config-ui-x
0|homebridge  | [10/2/2019, 8:53:38 PM] Registering platform 'homebridge-config-ui-x.config'
0|homebridge  | [10/2/2019, 8:53:38 PM] ---
0|homebridge  | [10/2/2019, 8:53:40 PM] Loaded plugin: homebridge-harmony
0|homebridge  | [10/2/2019, 8:53:40 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
0|homebridge  | [10/2/2019, 8:53:40 PM] ---
0|homebridge  | [10/2/2019, 8:53:46 PM] Loaded plugin: homebridge-hue
0|homebridge  | [10/2/2019, 8:53:46 PM] Registering platform 'homebridge-hue.Hue'
0|homebridge  | [10/2/2019, 8:53:46 PM] ---
0|homebridge  | [10/2/2019, 8:53:47 PM] Loaded plugin: homebridge-ifttt
0|homebridge  | [10/2/2019, 8:53:47 PM] Registering platform 'homebridge-ifttt.IFTTT'
0|homebridge  | [10/2/2019, 8:53:47 PM] ---
0|homebridge  | [10/2/2019, 8:53:49 PM] Loaded plugin: homebridge-nest
0|homebridge  | [10/2/2019, 8:53:49 PM] Registering platform 'homebridge-nest.Nest'
0|homebridge  | [10/2/2019, 8:53:49 PM] ---
0|homebridge  | [10/2/2019, 8:53:50 PM] Loaded plugin: homebridge-people
0|homebridge  | [10/2/2019, 8:53:50 PM] Registering platform 'homebridge-people.People'
0|homebridge  | [10/2/2019, 8:53:50 PM] Registering accessory 'homebridge-people.PeopleAccessory'
0|homebridge  | [10/2/2019, 8:53:50 PM] Registering accessory 'homebridge-people.PeopleAllAccessory'
0|homebridge  | [10/2/2019, 8:53:50 PM] ---
0|homebridge  | [10/2/2019, 8:53:50 PM] Loaded plugin: homebridge-plex-sensors
0|homebridge  | [10/2/2019, 8:53:50 PM] Registering platform 'homebridge-plex-sensors.Plex'
0|homebridge  | [10/2/2019, 8:53:50 PM] ---
0|homebridge  | [10/2/2019, 8:53:51 PM] Loaded plugin: homebridge-sonoff-tasmota-http
0|homebridge  | [10/2/2019, 8:53:51 PM] Registering accessory 'homebridge-sonoff-tasmota-http.SonoffTasmotaHTTP'
0|homebridge  | [10/2/2019, 8:53:51 PM] ---
0|homebridge  | [10/2/2019, 8:53:51 PM] Loaded plugin: homebridge-wol
0|homebridge  | [10/2/2019, 8:53:51 PM] Registering accessory 'homebridge-wol.NetworkDevice'
0|homebridge  | [10/2/2019, 8:53:51 PM] ---
0|homebridge  | [10/2/2019, 8:53:53 PM] Loaded plugin: homebridge-xiaomi-roborock-vacuum
0|homebridge  | [10/2/2019, 8:53:53 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
0|homebridge  | [10/2/2019, 8:53:53 PM] ---
0|homebridge  | [10/2/2019, 8:53:55 PM] Loaded plugin: homebridge-zp
0|homebridge  | [10/2/2019, 8:53:55 PM] Registering platform 'homebridge-lib.Lib'
0|homebridge  | [10/2/2019, 8:53:55 PM] Registering platform 'homebridge-zp.ZP'
0|homebridge  | [10/2/2019, 8:53:55 PM] ---
0|homebridge  | [10/2/2019, 8:53:55 PM] Loading 8 platforms...
0|homebridge  | [10/2/2019, 8:53:55 PM] [Config] Initializing config platform...
0|homebridge  | [10/2/2019, 8:53:55 PM] [Config] Spawning homebridge-config-ui-x with PID 31527
0|homebridge  | [10/2/2019, 8:53:55 PM] [Nest] Initializing Nest platform...
0|homebridge  | [10/2/2019, 8:53:55 PM] [Nest] Fetching Nest devices.
0|homebridge  | [10/2/2019, 8:53:55 PM] [Nest] Authenticating via Nest account.
...
0|homebridge  | [10/2/2019, 8:54:02 PM] [Nest] API subscribe POST: app launch
...
0|homebridge  | [10/2/2019, 8:54:05 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: undefined
0|homebridge  | [10/2/2019, 8:54:05 PM] [Nest] Retrying in 40 seconds.
...
0|homebridge  | [10/2/2019, 8:54:46 PM] [Nest] API subscribe POST: subscribing
0|homebridge  | [10/2/2019, 8:54:46 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: undefined
0|homebridge  | [10/2/2019, 8:54:46 PM] [Nest] Retrying in 40 seconds.
```

**Comment by adriancable** [comment] 2019-10-02 22:01
@Garywoo - please send me an email at adrian.cable@gmail.com. I'll send you some test code which (among other things) should give us some more information.

-Adrian

**Comment by Garywoo** [comment] 2019-10-02 22:12
Thanks @adriancable. I've reached out to you via email.

**Comment by adriancable** [comment] 2019-10-14 14:10
Resolved via email.

**Closed by adriancable** 2019-10-14 14:10 UTC

**Comment by acahir** [comment] 2019-12-01 01:50
I'm seeing the same error on a new install of homebridge-nest. Getting emails from Nest re new log-ins to my account, so seems to be authenticating. 

What was the solution to this?

**Comment by adriancable** [comment] 2022-11-15 19:58
@eoddc5 - this is not the same as the issue reported by the opener of this ticket.

ENOTFOUND is a DNS lookup error. It's a Nest service issue, an Internet provider issue, or a local network issue. It isn't something the plug-in has control over, sorry.

**Comment by Keagel** [comment] 2022-11-16 14:48
The same thing just started happening to me and I haven't changed anything. I checked my PiHole and the DNS requests aren't blocked.

**Comment by mkhome137** [comment] 2022-11-16 17:38
I also have the same problem with ENOTFOUND. It has started occuring since the evening of last Friday (11th November). It is intermittent and will have a period of maybe 30 minutes to 2 hours where HomeBridge seems to not work, then it will right itself. Any ideas would be much appreciated. Should this go to a different ticket? Many thanks. M

**Comment by mkhome137** [comment] 2022-11-16 18:06
Hi, thanks for such a rapid response. I'll have to ponder what to do next.

I don't think it's a local issue with my internet, I have put in a routine
that checks the internet connection once a minute and this shows no issues.
Homebridge also seems to be able to see the nest thermostat and view its
status, but I get the error when I try to change the temperature, but only
sometimes. It points to issues at the Google end, not homebridge

To be honest, I'd rather bin the nest thermostat completely, a hugely
flawed device with a wildly inaccurate and unpredictable thermometer.

Thanks for your assistance.
M

**Comment by setomerza** [comment] 2022-11-16 22:16
Also seeing this issue as described. Nothing changed on my end so I'm assuming it's a Nest Service problem.

> The same thing just started happening to me and I haven't changed anything. I checked my PiHole and the DNS requests aren't blocked.

**Comment by JulianLepinski** [comment] 2022-11-17 00:05
Yeah, just wanted to confirm that it seems like there are intermittent DNS issues with this domain that are not something the plugin can fix. I added some logging to see what URL is erroring out:

```
[11/16/2022, 7:04:18 PM] [Nest] [updateData] uri=https://czfe118-front01-iad01.transport.home.nest.com/v5/subscribe
[11/16/2022, 7:04:18 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: ENOTFOUND
[11/16/2022, 7:04:18 PM] [Nest] Retrying in 10 seconds.
```

And I've confirmed that this URL is indeed unreachable:

```
curl https://czfe118-front01-iad01.transport.home.nest.com/v5/subscribe
curl: (6) Could not resolve: czfe118-front01-iad01.transport.home.nest.com (Domain name not found)
```

Not sure why this is happening intermittently on Nest's end.

**Comment by MacularDegenerate** [comment] 2022-11-17 02:37
Like others, I started having this issue with my nest homebridge plugin starting on 11/15/22. 
'Nest API call to subscribe to device settings updates returned an error: ENOTFOUND'

Initially I attributed it to a power outage we had the night prior but since so many others are reporting the same thing it seems more likely to be a larger scale issue. Would be very interested if anyone finds a solution!

**Comment by adriancable** [comment] 2022-11-17 16:23
Homebridge UI is amazing but does not have the power to solve Nest cloud service issues, ISP issues or DNS caching issues. Sorry.

**Comment by InDoubt** [comment] 2022-11-17 16:44
All I know is I had this issue:
[11/17/2022, 10:49:30 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ENOTFOUND
And Nest wasn't working, among OTHER THINGS, all iOS Shortcut Automation were usseles. Just to mention one.
Then I installed the Homebridge UI v4.50.2 update, and Voilá!
Coincidence? Did the right thing? I don't know.
But this update was a game changer for me.
By the way, in my case, the issue started yesterday 16th after a Comcast outrage that lasted more then 7 hour in some areas of South Florida.
I just wanted to share my experience and not trying to say that this is the solution. I'm totally illiterate in comparison with you guys. Just a regular user.
Cheers!

**Comment by MacularDegenerate** [comment] 2022-11-18 02:02
I did not update anything but restarted Homebridge from the web UI and that actually seemed to solve the problem for me as well. I am still seeing various intermittent Nest error codes within my Homebridge Logs (ENOTFOUND, 400, 502...), but the thermostat is back in my Accessories list and functioning within Homekit as expected. ¯\_(ツ)_/¯

**Comment by mkhome137** [comment] 2022-11-23 15:38
This was an intermittent fault so hard to diagnose. I still don't know if it back on track. I still don't know whether it is something that Google are fixing at the Nest API end, or whether anything I am doing is improving things.

It is clear that it is not a Homebridge issue, Homebridge is simply the messenger giving me the bad news about the inability for my raspberry pi to see the Nest API server.

I restarted homebridge. The calls to Google to change my Nest temperature started working, but after a few hours I got ENOTFOUND again. Rats!

So:
I have updated node.js from version 16 to the latest stable version - 18. 
I have changed my DNS settings to point to the Google provided DNS server.
I have rebooted and restarted.
Yesterday the Google Nest API went down completely for a few hours and didn't work from anywhere (Alexa voice commands, browser or Nest android app). Which was a fun diversion just as I was ready to test my changes. 
It is now back up and running and so far today all seems well.

I have also changed the code in my heating control application:
- to check the last few lines of the Homebridge log file to confirm any changes I request have a positive response. 
- if any issues occur I have a backup method where I play a WAV of my voice in a small speaker next to my Amazon Echo to reset the Nest temperature (fine as long as the Nest API is still visible to Amazon)
- to specifically check for the ENOTFOUND message in the Homebridge log file. If it occurs 2 or more times in 30 minutes I issue a command to restart Homebridge

Again, thanks to Adrian for his rapid and helpful response, I hope my adding to a long-dead thread isn't a distraction.

**Comment by InDoubt** [comment] 2022-11-23 18:28
Thank you for sharing, mkhome.
My plugin still working fine, but ENOTFOUND messages are showing on again. Even though, I still can control without problems my thermostat from the Home app in any device around the house and the phone. Even my Shortcuts app automations that run every 1/2 hour to  control Nest, work without hiccups.  I want to add that I use Nest Account with an access token. (The original. Not Google) and I have noticed that, Wize Home plugin is also showing those ENOTFOUND messages every so often, every day, but haven't notice any dysfunction with the Wize switches controled from the Home app.
