### ISSUE TITLE
Using HOOBS MAC App issue

### ISSUE THREAD

**Issue by pruveit** [chrisjshull/homebridge-nest#477] opened 2021-12-03 19:56 UTC
Hi,

I've tried to use the HOOBS app and the Configurator.
I have LINKED my accounts based on the apps Link request feature and no success. The HOOBS app shows that the account is linked and has the ability to UNLINK ACCOUNT.

I tried unlinking and linking it back just to see if there would be a change, no success.

Thanks for any help.

JP

**Comment by adriancable** [comment] 2021-12-03 19:58
Duplicate of #452 and several others. Also, I do not use HOOBS and cannot help you with HOOBS problems. Please talk to HOOBS. Thanks.

**Closed by adriancable** 2021-12-03 19:58 UTC

**Comment by pruveit** [comment] 2021-12-03 20:05
Sorry I missed #452, I'll do just that. Thank you.
