### ISSUE TITLE
Nest Thermostat in Cooling ECO mode shows “Heating”

### ISSUE THREAD

**Issue by mbhforum** [chrisjshull/homebridge-nest#126] opened 2019-08-07 13:01 UTC
**Describe the bug**

When my thermostat goes into ECO mode (which is done natively through Nest) it shows as Heating in HomeKit even though it’s cooling.  I do have The ECO switch disabled in my configuration.

**To Reproduce**
1.  Let Nest Thermostat go into ECO mode and observe incorrect display on my dashboard.  

**Expected behavior**

Should display ECO mode.  

Include with your bug report this version info:
```sh
node --version
homebridge --version
```
Using Docker image on my Synology:   https://hub.docker.com/r/marcoraddatz/homebridge/

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment] 2019-08-07 13:10
Thanks for the report. This is strange! Can you please do this:

1. Add "Debug.Verbose" to "options" in config.json
2. Run: homebridge -D
3. Get me a screenshot of the Home app when this is happening, and also a screenshot of the Nest app when this is happening, showing the inconsistency.
4. Send me the output from homebridge.

Please send all this to adrian.cable@gmail.com. Thanks!

Thanks!

**Comment by mbhforum** [comment] 2019-08-07 14:19
I figured out the issue.  I had an ECO setting defined for Heat on the Thermostat, but not for Cool which I fixed, which now resolved the issue showing "heating".  You can probably easily reproduce this behavior. I recommend it display "Eco" somewhere in the icon, but not sure if that is a Homekit limitation.

**Comment by adriancable** [comment] 2019-08-07 14:42
OK great - sounds like all is working as intended. Unfortunately with HomeKit there's no way to indicate Eco mode, if you have the Eco Mode accessory switch disabled - I understand that can be a confusing limitation.

Closing for now.

**Closed by adriancable** 2019-08-07 14:42 UTC
