### ISSUE TITLE
Automation to set heat + temp actually set cool + temp

### ISSUE THREAD

**Issue by AlexPygin** [chrisjshull/homebridge-nest#486] opened 2021-12-23 16:49 UTC
**Describe the bug**
I setup an automation to heat my house in the morning, but last night it didn't. After the last bug that we resolved together I stopped using the Nest application entirely and have only been using Home app. In general everything has been 100% stable except for this issue that just occurred last night. I attached the simple automation that was there, and the logs showing that it set heat, then temp, then set it to cool. I figured I'd create this issue right away in case we need to do some more long term troubleshooting.

**To Reproduce**
This has only happened once, but I would wager it was because the nest was on cooling mode before the automation ran

**Expected behavior**
Like the previous 15 or so days since I set this up, I wake up to a heated house

Include with your bug report this version info:
```sh
node --version
homebridge --version
```
Node: v14.17.0
Homebridge: 1.3.8
homebridge-nest: v4.6.3

![IMG_0358](https://user-images.githubusercontent.com/7217751/147269233-28cb40a4-f94f-425f-94ca-b2c49e27b5fa.jpg)
![IMG_0359](https://user-images.githubusercontent.com/7217751/147269237-3c03845a-978b-447a-9eff-f0bf6f9c80c6.jpg)

**Comment by adriancable** [comment] 2021-12-23 17:28
@AlexPygin - thanks for reporting and sorry this happened to you. It isn't nice to wake up to a cold house!

The log is completely normal. It doesn't (as you say) "logs showing that it set heat, then temp, then set it to cool". It shows setting heating threshold, setpoint and cooling threshold together which is normal in any mode when the temperature is changed. In fact, the log screenshot doesn't show any mode change at all.

When you woke up and things weren't right, did you actually look at the thermostat to see what it was set to? Was it set to cool, or off, or heating but to the wrong temperature, or heating to the right temperature but not actually heating?

To make any progress, you'd need to be able to reproduce this (and ideally log in debug verbose mode, the way we did before). Are you able to reproduce this using the 'Test this automation' button?

**Comment by AlexPygin** [comment] 2021-12-23 17:29
It was set to Cool, 72 when I checked in the morning.

Lemme turn on debug logs again and try to repro

**Comment by adriancable** [comment] 2021-12-23 17:32
@AlexPygin - thanks. Given we don't see a mode change in the log, the issue may be that (for whatever reason) HomeKit didn't send a mode change command, along with the temperature change command which the plug-in did receive, and act upon. However, if there was a mode change it may well have been off the bottom of your screenshot, since unfortunately it gets cut off after the 'set cooling threshold' entry (which is normal & expected).

**Comment by AlexPygin** [comment] 2021-12-23 17:32
"However, if there was a mode change it may well have been off the bottom of your screenshot"

That was the bottom of the log file for what it's worth

**Comment by AlexPygin** [comment] 2021-12-23 17:37
Well I tried some scenarios that could have occurred but couldn't repro, so I'll keep debug logs on and see if it will happen again with debug logs on. 

1. Set to cool, run automation
2. Set to cool at 81 degrees, run automation
3. Set to off, run automation
4. Set to cool at 81 degrees, then off, run automation

**Comment by AlexPygin** [comment] 2021-12-29 15:40
I'll blame this on my internet connection being down when the automation is supposed to run.

**Comment by AlexPygin** [comment] 2021-12-31 16:11
https://gist.github.com/AlexPygin/bff291833a57195779ce34b623dc94a3

Woke up today with nest set to 72 and cool again instead of 72 and heat, and I have the logs

**Comment by adriancable** [comment] 2021-12-31 16:29
Alex - thanks for the log. Will take time to digest but an initial glance does seem to suggest some sort of bug in the plug-in. I’ll keep you updated.

**Comment by adriancable** [comment] 2022-01-28 21:18
Fixed in 4.6.4, now released.

**Closed by adriancable** 2022-01-28 21:18 UTC
