### ISSUE TITLE
Nest API call to subscribe to device settings updates returned an error: 400

### ISSUE THREAD

**Issue by jsalva23** [chrisjshull/homebridge-nest#380] opened 2021-03-01 21:16 UTC
hi,

I'm using a raspberry Pi 3 with HOOBS installed version 3.3.2, Node version 12.14.1, its been running ok so far, I have several plugins for other devices and I only use this Nest plugin to have visibility and interact with my Nest protect V2 smoke/carbon monoxide detectors in Homekit, those are the only NEST products I own and all of them but one are battery powered and just one wired. About about a week ago I updated the NEST plugin to version 4.5.2 and since then I have two problems:

1. In the log section I keep getting the same error: Nest API call to subscribe to device settings updates returned an error: 400        Retrying in 10 seconds.

2. The only wired Nest protect I have as you know also provides visibility for the occupancy sensor and that seems to be working the other way around, I was off mid week for a couple of days and the entire time the sensor was reporting occupancy in the room its installed in the Home app but now that I'm in its not reporting occupancy.

I see a similar issue under the issue Homebridge 1.3.0 in the issues list, not sure if this is related to a hombridge update, however I have not updated HOOBS just the plugin.

Thanks in advance for your help

**Comment by adriancable** [comment] 2021-03-01 21:24
@jsalva23 - can you kindly email me at adrian.cable@gmail.com and we'll try and work through this. Thanks!

**Comment by adriancable** [comment] 2021-03-02 22:29
I have got to the bottom of this. It is due to the fact that, on HOOBS, all plug-ins share a common global Axios object, and homebridge-sensibo-ac overwrites the global properties causing the Sensibo AC API key to be added to requests sent by ALL other plug-ins, instead of creating its own Axios instance and doing it there. I have reached out to the homebridge-sensibo-ac developer @nitaybz and hopefully he will fix it. Watch this space!

**Comment by adriancable** [comment] 2021-03-03 21:15
Confirmed fixed by homebridge-sensibo-ac plug-in version 2.1.1.

**Closed by adriancable** 2021-03-03 21:15 UTC

**Comment by jsalva23** [comment] 2021-03-03 21:47
@adriancable, I can confirm the issue is fixed now. Thanks a lot for your fast response and initiative to fix this, even after discovering it wasn't actually your plugin the one with an error, thank you for engaging the developer of the other plugin and suggesting a fix.

Thanks!!!

**Comment by adriancable** [comment] 2021-03-03 21:49
Sure thing! I very much appreciate your help in debugging this. It was an odd one!
