### ISSUE TITLE
Google Nest API Use

### ISSUE THREAD

**Issue by rroach3753** [chrisjshull/homebridge-nest#337] opened 2020-11-24 19:17 UTC
I have paid a $5 to google to access an API key.  Will you be updating to include API access as you do for regular Nest accounts?  I would love to see this happen!  I regularly flush my cache, history, and logins, and I always have to reconfigure homebridge.

**Comment by adriancable** [comment] 2020-11-24 19:26
This is basically a duplicate of #305. Sorry, we have no intention to support the Google Device Access API in the near future. It would be a huge undertaking, and would lead to significantly reduced functionality (no Protect support, no Lock support, no Nest account support). The effort/return equation is just hugely negative.

**Closed by adriancable** 2020-11-24 19:26 UTC
