### ISSUE TITLE
Link Account not working

### ISSUE THREAD

**Issue by MandAtaco** [chrisjshull/homebridge-nest#458] opened 2021-10-30 02:03 UTC
**Describe the bug**
Unable to link accounts. Everytime I try to link the acount it brings up a blank screen but never progresses anywhere. Tried multiple browsers, In congneto mode, pop up blocker turned off and no dice. Hoobs is up to date, and downloaded the latest version of the plugin. Thanks!

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment] 2021-10-30 02:06
Duplicate of #452.

**Closed by adriancable** 2021-10-30 02:06 UTC
