### ISSUE TITLE
This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response

### ISSUE THREAD

**Issue by jennings** [chrisjshull/homebridge-nest#379] opened 2021-02-25 19:49 UTC
When turning on the fan from HomeKit, Homebridge generates the warning:

> This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response.

The fan **does** turn on properly.

The only feature option I'm using is `HomeAway.AsOccupancySensor`.

# Version info

homebridge-nest v4.5.2

```sh
/homebridge # node --version
v14.15.1
/homebridge # homebridge --version
Initializing HAP-NodeJS v0.9.2...
1.3.1
```

# Debug log

```
[2/25/2021, 11:40:30 AM] [Nest] Setting target fan state for Kitchen Thermostat to: true
[2/25/2021, 11:40:30 AM] [Nest] Setting fan enable/disable for Kitchen Thermostat to: true
[2/25/2021, 11:40:30 AM] [Nest] device.############## fan_timer_active true
[2/25/2021, 11:40:31 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[2/25/2021, 11:40:31 AM] [homebridge-nest] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1645:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-nest/index.js:16:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by adriancable** [comment] 2021-02-25 22:13
@jennings - thanks for this - I will fix it in the next update. For now, don't worry - the warning is completely harmless.

**Comment by soulcook** [comment] 2021-02-25 23:32
Just FYI, I'm getting something very similar:

[2/25/2021, 8:57:42 PM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[2/25/2021, 8:57:42 PM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

Keeps appearing in the log.

**Comment by ValoV83** [comment] 2021-03-01 17:12
I'm getting the above error as well.

[homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

I'm assuming everything is ok, as all change of temperature command either manually or by Siri are carried out ok.

**Comment by shimi269** [comment] 2021-03-05 13:45
Same issue

[3/5/2021, 1:14:48 PM] [Nest] Setting temperature to 25 °C / 77 °F
[3/5/2021, 1:14:48 PM] [Nest] Setting target temperature for Upstairs Thermostat to: 25
[3/5/2021, 1:14:48 PM] [Nest] shared.6416660000A21D74 target_temperature 25
[3/5/2021, 1:14:48 PM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/5/2021, 1:14:48 PM] [homebridge-nest] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1645:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-nest/index.js:16:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/5/2021, 1:14:48 PM] [Nest] Target temperature for Upstairs Thermostat is: 25 °C / 77 °F
[3/5/2021, 1:14:50 PM] [homebridge-nest-cam] Checking for alerts on Front Door
[3/5/2021, 1:14:51 PM] [Hue] Philips hue: request 13: GET /lights
[3/5/2021, 1:14:51 PM] [Hue] Philips hue: request 13: 200 OK
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Person Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Package Delivered Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Person Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Package Delivered Motion to false
[3/5/2021, 1:14:51 PM] [Nest] Cooling threshold temperature for Upstairs Thermostat is: 25 °C / 77 °F
[3/5/2021, 1:14:51 PM] [Nest] Heating threshold temperature for Upstairs Thermostat is: 25 °C / 77 °F

**Comment by marked80** [comment] 2021-03-05 21:17
After updating to 4.5.3 the warning is still in the log:
[3/5/2021, 10:14:00 PM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**Comment by adriancable** [comment] 2021-03-05 22:14
@marked80 - what switch are you controlling to produce this warning? (which is safe to ignore)

**Comment by marked80** [comment] 2021-03-06 03:52
@adriancable I am using the “home occupied” switch for the Nest thermostat

**Comment by adriancable** [comment] 2021-03-06 15:26
@marked80 - are you sure you're running the latest version of the plug-in, 4.5.3? (You say you updated - is it possible that update failed somehow and you're still on an earlier version, or that you now have multiple versions of the plug-in installed?) Please check and let me know. Easiest way is to look at Homebridge's output when it starts up - it will tell you the plug-in version in use Thanks!

**Comment by marked80** [comment] 2021-03-06 16:04
Hi Adrian, I checked and is is really run 4.5.3 see attached screenshot. 
![A8FA71CF-36CA-401E-AEE7-BBDC1F7E6406](https://user-images.githubusercontent.com/73982879/110212930-fdec0200-7e9d-11eb-8d12-5d867925df00.jpeg)

**Comment by adriancable** [comment] 2021-03-06 16:17
@marked80 - this is so strange. I've looked through the code and the 'Home Occupied' set handler really can't return a value (there's no 'return' statement at all). Is it possible that you have e.g. an automation which triggers when you move the 'Home Occupied' switch and controls another accessory, and it's that accessory that produces the warning?

Could you kindly reproduce the warning message, and then send a screenshot (like the above) showing the warning, with a few lines before and a few lines after for context. Thank you!

**Comment by marked80** [comment] 2021-03-06 16:27
Hi, I just reproduced the issue. 
 I have an automation that when movement is detected the home occupied switch is set to true. When the switch is set to false and then set to true there is no warning. When it is already true and then switched to true again it generates the warning.

**Comment by 1004PTLN** [comment] 2021-03-06 16:54
@adriancable see below.  Same behavior, seems to be on switches.  Verified I'm on 4.5.3, hen toggled FAN and ECO switches in several rooms (eg nest zones).  For what it's worth I have 3 of the 1st gen nest thermostats.  


[3/6/2021, 10:41:29 AM] Loaded plugin: homebridge-nest@4.5.3
[3/6/2021, 10:41:29 AM] Registering platform 'homebridge-nest.Nest'


[3/6/2021, 10:43:02 AM] [Nest] Setting target fan state for Family Room Thermostat to: true
[3/6/2021, 10:43:02 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:46:39 AM] [Nest] Setting target fan state for Family Room Thermostat to: false
[3/6/2021, 10:46:39 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:46:47 AM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/6/2021, 10:46:47 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:48:24 AM] [Nest] Setting Eco Mode for Family Room Thermostat to: heat
[3/6/2021, 10:48:24 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:12 AM] [Nest] Setting target fan state for Family Room Thermostat to: true
[3/6/2021, 10:49:12 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:25 AM] [Nest] Setting target fan state for Family Room Thermostat to: false
[3/6/2021, 10:49:25 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:34 AM] [Nest] Setting Eco Mode for Basement Thermostat to: eco
[3/6/2021, 10:49:34 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:36 AM] [Nest] Setting Eco Mode for Basement Thermostat to: heat
[3/6/2021, 10:49:36 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:40 AM] [Nest] Setting target fan state for Basement Thermostat to: true
[3/6/2021, 10:49:40 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 10:49:44 AM] [Nest] Setting target fan state for Basement Thermostat to: false
[3/6/2021, 10:49:44 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**Comment by adriancable** [comment] 2021-03-06 17:30
@1004PTLN - thanks for the extra info - this is helpful. Again please note you can completely ignore this warning, but I do want to address it as it's distracting. Will need a little digging.

**Comment by 1004PTLN** [comment] 2021-03-06 17:47
Completely understand and thank you for all of your efforts on this terrific plug-in!

**Comment by soulcook** [comment] 2021-03-06 20:20
FYI -- I'm getting the same thing, with the latest version:

```
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 21 °C / 69.8 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 21 °C / 69.8 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 21 °C / 69.8 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 22 °C / 71.60000000000001 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 21 °C / 69.8 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting temperature to 21 °C / 69.8 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting cooling threshold temperature to 24 °C / 75.2 °F
[3/6/2021, 7:59:59 AM] [Nest] Setting heating threshold temperature to 20 °C / 68 °F
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 7:59:59 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
```

- OS: MacOS 11.2.1
- Node.js: v14.15.5
- NPM: v6.14.11
- homebridge-nest v4.5.3
- homebridge: v1.3.2

**Comment by 1004PTLN** [comment] 2021-03-10 22:13
@adriancable I just wanted to follow up on this issue.  I just updated homebridge to v1.3.3 and proceeded to check a variety of the nest toggle buttons and got no errors.   Wanted to let you know.  

[3/10/2021, 3:58:58 PM] Homebridge v1.3.3 (Homebridge AB1E) is running...

[3/10/2021, 4:01:46 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/10/2021, 4:01:49 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: heat
[3/10/2021, 4:01:51 PM] [Nest] Setting target fan state for Family Room Thermostat to: true
[3/10/2021, 4:01:55 PM] [Nest] Setting target fan state for Family Room Thermostat to: false
[3/10/2021, 4:08:04 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/10/2021, 4:08:10 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: heat
[3/10/2021, 4:09:18 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/10/2021, 4:09:21 PM] [Nest] Setting target fan state for Family Room Thermostat to: true
[3/10/2021, 4:09:25 PM] [Nest] Setting target fan state for Family Room Thermostat to: false
[3/10/2021, 4:09:27 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: heat
[3/10/2021, 4:09:33 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/10/2021, 4:09:35 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: heat
[3/10/2021, 4:09:41 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: eco
[3/10/2021, 4:09:42 PM] [Nest] Setting Eco Mode for Family Room Thermostat to: cool
[3/10/2021, 4:09:47 PM] [Nest] Setting target fan state for Family Room Thermostat to: true
[3/10/2021, 4:09:49 PM] [Nest] Setting target fan state for Family Room Thermostat to: false

**Comment by marked80** [comment] 2021-03-13 00:56
Hi @adriancable, my warning messages are gone also since the upgrade to homebridge 1.3.3. Seems like the “issue” is solved

**Comment by adriancable** [comment] 2021-03-13 01:33
Very happy to hear HB 1.3.3 resolves this. Closing for now.

**Closed by adriancable** 2021-03-13 01:33 UTC

**Comment by pricejordan41** [comment] 2022-01-21 01:40
I am seeing the same error message when adjusting the temperature of my nest thermostat. 

Running 4.6.3 version. 
Node version 14.18.1

`1/20/2022, 7:28:37 PMNest Thermostat Nest Thermostat Setting temperature to 22.2 °C / 71.96000000000001 °F
1/20/2022, 7:28:37 PMNest Thermostat ERROR[Nest Thermostat  0268@Hallway Thermostat@@Target Temperature] SET handler returned write response value, though the characteristic doesn't support write response
1/20/2022, 7:28:41 PMNest Thermostat Nest Thermostat Setting temperature to 22.8 °C / 73.04 °F
1/20/2022, 7:28:41 PMNest Thermostat ERROR[Nest Thermostat  0268@Hallway Thermostat@@Target Temperature] SET handler returned write response value, though the characteristic doesn't support write response
1/20/2022, 7:29:10 PMNest Thermostat Nest Thermostat Setting temperature to 28.900000000000002 °C / 84.02 °F
1/20/2022, 7:29:10 PMNest Thermostat ERROR[Nest Thermostat  0268@Hallway Thermostat@@Target Temperature] SET handler returned write response value, though the characteristic doesn't support write response
1/20/2022, 7:29:13 PMNest Thermostat Nest Thermostat Setting temperature to 22.8 °C / 73.04 °F
1/20/2022, 7:29:13 PMNest Thermostat ERROR[Nest Thermostat  0268@Hallway Thermostat@@Target Temperature] SET handler returned write response value, though the characteristic doesn't support write response`

Any ideas?

**Comment by adriancable** [comment] 2022-01-21 02:17
@pricejordan41 - do you actually have a functional problem with the plug-in, or is it just that you find the message ugly? If the latter, please just ignore it. Plug-in log messages are intended for me (the developer), not you.

**Comment by dillonp23** [comment] 2022-03-31 18:48
Hey @adriancable - I'm developing a platform plugin that has a Thermostat service (not Nest - different product) and I'm running into this error. It's my 1st time making an HB plugin & I'm an iOS developer (Swift), so Typescript/JS/Node/etc is all new to me.

I'm wondering if you figured out what was causing this problem? Just curious if it's a bug in my plugin's code, or an issue with Homebridge itself, before I waste a bunch of time debugging. Let me know when you get a chance, thank you!

P.S. I love this plugin - using it for my Nest at home, works fantastically for me.

**Comment by MorelloCherry** [comment] 2023-05-30 09:51
It appears that this issue "SET handler returned write response value, though the characteristic doesn't support write response" is not yet solved or has reappeared as I can see it now (30/05/2023).
