### ISSUE TITLE
Incompatible with iOS 14 and 14.0.1

### ISSUE THREAD

**Issue by CipherTheWolf** [chrisjshull/homebridge-nest#308] opened 2020-09-25 17:41 UTC
After update to the new Apple OS’s the plugin breaks the ability to pair HomeBridge or HOOBS to the Home app (HomeKit). When you add the bridge with the plugin configured you get an error that an “accessory is out of compliance.” When you uninstall the plugin, you are able to add the bridge. If you attempt to add the plugin after pairing HomeKit and the bridge you loose the connection to all bridge plugins. Sorry, don’t have the time right now to produce debug report, will try to update with it later. I have seen thought this is not isolated to me as there are other forums talking about this same issue.

**Comment by adriancable** [comment] 2020-09-25 17:46
@CipherTheWolf - thanks for your note. This is strange and the first I've heard about it. I'm not able to reproduce it here on iOS 14.

Can you share screenshots of this error? Also, debug logs from Homebridge would be very useful. Also please can you share your complete list of Nest devices. Thanks!

**Comment by gtg465x** [comment] 2020-09-25 18:39
This happened to me as well. In my case, I updated my iPhone to iOS 14 and everything was working fine for a while, but then I logged in to HOOBS and updated the Nest plugin from (I think) 4.4.6 to 4.4.9, and after that, all of my homebridge devices, not just Nest devices, started showing "No Response". I then tried the "Reset Connection" button in HOOBS, which deletes the persist folder and disconnects from your Apple Home. Then, when I tried to re-pair homebridge to my Apple Home, I got the "accessory is out of compliance" error. I then uninstalled the homebridge-nest plugin, and was then able to re-pair, and all of my homebridge devices started responding again. Now I'm afraid to re-install homebridge-nest because I don't know what the heck happened and I ended up having to set up all of my automations again, which took forever. There were no errors in the logs during any of this, but I never attempted to enable any additional debug logging or anything.

**Comment by adriancable** [comment] 2020-09-25 18:53
@gtg465x - can you share what version of Homebridge you are using?

I am pretty sure that this behavior is triggered by a specific combination of factors, not just plug-in version. The plug-in has tens of thousands of users, thousands (I would expect) are now on 4.4.9 and running iOS 14 and so clearly for most people that combination works. (And I include myself in the list of iOS 14 users for whom the plug-in works - in my case using Homebridge 1.2.3.)

Also I would be interested if anyone has experienced this just running vanilla Homebridge (i.e. not HOOBS). It feels unlikely that something specific to HOOBS could be responsible for this, but right now eliminating common factors is useful since I don't have many other leads.

**Comment by adriancable** [comment] 2020-09-25 19:02
@CipherTheWolf / @gtg465x - if either of you have a little time and are comfortable with following my instructions to edit Javascript files on your HOOBS system, please email me at adrian.cable@gmail.com as there are a couple of things we can try.

**Comment by gtg465x** [comment] 2020-09-25 20:07
@CipherTheWolf So apparently, HOOBS decided to obfuscate which version of homebridge it's running at some point. It used to show the homebridge version right on the main UI page, but now I can't find it anywhere in the UI, and I wasn't even able to figure out by doing a quick search through their source, so who knows. Now I kind of wish I wouldn't have spent half a day yesterday setting up all of my automations again with HOOBS. Probably should have switched to just running homebridge directly on my Pi 4 B.

I'll let you know if I build up the stamina to start trying things. The wounds are still fresh from spending a long time re-setting up all of my homebridge devices and automations yesterday.

Also, I found this issue is also posted to the HOOBS GitHub page, so this might be an issue that only affects HOOBS users, or users running older versions of homebridge. https://github.com/hoobs-org/HOOBS/issues/810

**Comment by gtg465x** [comment] 2020-09-25 23:46
@adriancable Uh oh, it's not HOOBS or the homebridge version. I just did a fresh install using the latest homebridge-raspbian-image (https://github.com/homebridge/homebridge-raspbian-image), which contains homebridge 1.2.3, and I installed and configured homebridge-nest and then tried to pair homebridge to my Apple Home and got the same out of compliance error.

**Comment by adriancable** [comment] 2020-09-25 23:49
@gtg465x - if you have 15 minutes or so over the weekend, please email me at adrian.cable@gmail.com and I'll give you some instructions to record a log that might help troubleshoot.

What seems to be clear is there's no single factor causing this issue. It's not just the plug-in version, the iOS version, the Homebridge version etc. as there are many people with each of those without issues.

**Comment by gtg465x** [comment] 2020-09-26 00:07
@adriancable Sent you an email with some logs. Let me know what else I can provide

**Comment by adriancable** [comment] 2020-09-26 01:57
Just to let everyone know that I am getting quite close to figuring this one out and updating the plug-in with a resolution. Will be within the next 24 hours.

**Comment by adriancable** [comment] 2020-09-26 02:19
This is now fixed (I hope!) in 4.4.10. The cause is that a small number of Temperature Sensors appear not to have serial numbers, and HomeKit does not allow serial numbers for accessories to be blank. Will leave this open while people update, then will close when everything settles down.

**Comment by CipherTheWolf** [comment] 2020-09-26 03:18
Just got home to do some investigations and to get you data, but I saw this. I updated installed and it worked like a charm! You all are amazing! Thank you so much!!!

**Closed** 2020-09-29 14:46 UTC
