### ISSUE TITLE
4.4.9 not installing.... 4.4.6 seems to be latest

### ISSUE THREAD

**Issue by BadMelonFarmer** [chrisjshull/homebridge-nest#303] opened 2020-09-09 19:42 UTC
Not sure if it is just me, but trying to install via usual methods homebridge-config-ui-x and or npm install -g homebridge-nest via command line directly.

Just installs 4.4.6, says not update available.

Has the update process changed?

Same happened with 4.4.7 and 4.4.8.

Other plugins are updating fine

**Comment by adriancable** [comment] 2020-09-09 23:27
Duplicate of #300.

**Comment by adriancable** [comment] 2020-09-10 01:00
Now published to npm! Thanks for your patience.

**Closed by adriancable** 2020-09-10 01:00 UTC

**Comment by BadMelonFarmer** [comment] 2020-09-10 07:25
Thank you
