### ISSUE TITLE
This plugin generated a warning from the characteristic 'Heating Threshold Temperature'

### ISSUE THREAD

**Issue by rraymond1970** [chrisjshull/homebridge-nest#430] opened 2021-09-22 05:18 UTC
Log Error:

[homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.444444444444445 exceeded minimum of 10. See https://git.io/JtMGR for more info.

**To Reproduce**
1. View in log

**Expected behavior**

Include with your bug report this version info:
```sh
node --version -- 14.17.6
homebridge --version -- 1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`[homebridge.log.txt](https://github.com/chrisjshull/homebridge-nest/files/7207903/homebridge.log.txt)`

**Comment by adriancable** [comment] 2021-09-22 05:20
This is a duplicate of #389 which is pinned for your convenience.

**Closed by adriancable** 2021-09-22 05:20 UTC
