### ISSUE TITLE
Temperature decimal points

### ISSUE THREAD

**Issue by rayr007** [chrisjshull/homebridge-nest#321] opened 2020-10-15 17:43 UTC
I noticed that despite having my house set to heat at 21.5°C, the home app reported that it was heating to 21°C. Is there a bug in the plugin where the decimal is getting cut off (perhaps taking data as in int instead of decimal somewhere)? Or is this a bug with Apple's Home app?

**Comment by nitronl** [comment] 2020-10-17 20:05
Same goes for the room temperature read off the thermostat sensor via homebridge. It is 0.5 degrees Celsius lower than indicated in the Nest app.

**Comment by adriancable** [comment] 2020-10-18 01:43
I looked into this a while ago (a couple of years) and it turns out that the Nest app rounds temperatures up to the nearest 0.5 deg C, whereas HomeKit rounds temperatures to the nearest 0.5 deg C. So if for example the house temperature is actually 21.2 deg C, the Nest app will say 21.5 deg C whereas HomeKit will say 21.0 deg C.

**Comment by nitronl** [comment] 2020-10-18 05:37
Then it is strange why the delta also applies when setting the thermostat temperature. Nothing to round there.

**Comment by adriancable** [comment] 2020-10-24 16:29
I'll take a look again at this since I seem to remember it's quite easily reproducible, and report back with more detail on what's actually happening.

**Comment by adriancable** [comment] 2020-10-25 00:08
@rayr007 / @nitronl - we have a candidate fix for the decimal point rounding issue. If you are interested in testing, please email me at adrian.cable@gmail.com. Thanks!

**Comment by adriancable** [comment] 2020-10-26 22:36
Now fixed in 4.4.13.

**Closed by adriancable** 2020-10-26 22:36 UTC
