### ISSUE TITLE
When Google credentials change, Homebridge forgets all the accessories

### ISSUE THREAD

**Issue by soulcook** [chrisjshull/homebridge-nest#290] opened 2020-08-08 10:58 UTC
This is a great plugin, and many thanks for creating it. But...

My Google cookie value regularly changes, even though I never log out of Nest or Google. This seems to happen in particular whenever there is a system software update on any of my devices. I then have to go through the whole process of retrieving the credentials and updating the homebridge-nest config.

The most tedious part is that as soon as the credentials are invalidated, Homebridge forgets all my Nest devices (I have lots). After I update the credentials, all the devices then re-appear in the default room and I have to reassign them all to the correct rooms. They also disappear from all automations, and I have to laboriously put them all back in. It's a real pain. Is there anything that can be done about this?

Note: the devices persist just fine when Homebridge is restarted. It's just when the credentials are invalid that they disappear.

To reproduce, simply log out of Home and log back in again. The credentials will then be invalid for homebridge-nest, and it will forget all its devices. Update the credentials in homebridge-nest config, and the devices will reappear but as new devices.

Node v12.16.3
Homebridge v1.1.1

**Comment by adriancable** [comment] 2020-08-08 11:11
Hi @soulcook - this is basically a duplicate of #263, and there's a long discussion there of why this happens you might want to read. Further feedback is very welcome.

The solution is simple (lock homebridge on start if the credentials are faulty, rather than returning an empty accessories array), unfortunately, this is how the plug-in used to work and people weren't happy with that, which is why I changed it to the present behaviour ... but that (understandably) also makes people unhappy. So not really clear what the right approach is. Maybe provide a switch in the config to choose between the two.

**Comment by soulcook** [comment] 2020-08-08 11:25
HI Adrian

Many thanks for the quick response.

I assumed this was different from #263
<https://github.com/chrisjshull/homebridge-nest/issues/263>, because it
only happens on credentials failure not on normal restart, but on reading
the whole thread I see that it's the same. I will close it.

Having read your very clear explanation I now understand the problem. It's
a great shame that in the failure state the accessories don't return "no
response" in your "option 3" (return cached accessory array), since if they
did this would clearly be the ideal solution.

May I ask a question? When authorisation initially fails, all the affected
accessories come up with helpful exclamation marks. How do they acquire
that attribute? And why can't they acquire it again following a reboot with
a cached accessory array?

Just wondering...

Paul

**Comment by Nastras** [comment] 2020-08-11 04:13
That would be great if you can put a choice in the config.

I have exactly the same problem that at irregular intervals the cookie changes and all devices in homekit are removed.
So it doesn't make sense to include the nest devices in automations anymore.
Would be really great if you could do it?

Thanks a lot!

**Comment by neilmorton** [comment] 2020-08-11 08:32
> Hi @soulcook - this is basically a duplicate of #263, and there's a long discussion there of why this happens you might want to read. Further feedback is very welcome.
> 
> The solution is simple (lock homebridge on start if the credentials are faulty, rather than returning an empty accessories array), unfortunately, this is how the plug-in used to work and people weren't happy with that, which is why I changed it to the present behaviour ... but that (understandably) also makes people unhappy. So not really clear what the right approach is. Maybe provide a switch in the config to choose between the two.

@adriancable I would certainly agree that a config switch would be good, as it is annoying to see the devices lost and have to reconfigure automations / rooms / etc every time this happens (which seems to have become more frequent). 

Thanks!

**Comment by soulcook** [comment] 2020-08-11 10:23
This does seem like a serious, and increasingly frequent, problem.

Can anyone answer my question (above)?

> When authorisation initially fails, all the affected accessories come up with helpful "not responding" messages in the Home app. How do they acquire that attribute? And why can't they acquire it again following a reboot with a cached accessory array?

Thanks

**Comment by gdotp01** [comment] 2020-08-26 14:13
I must say that its seems like Google are asking for credentials more often these days. It is a pain it just dropping the accessories because any automations that include these break. It would be better I think to have a switch that allows us to choose the failure method or better still if the plugin could cope with the auth failure and simply put the Nest switched in as 'no response' *(although I appreciate that saying this is probably more simple than coding it (or it would have been done in the first place)

**Comment by adriancable** [comment] 2020-09-02 19:58
Consolidated under #299.

**Closed by adriancable** 2020-09-02 19:58 UTC
