### ISSUE TITLE
Nest AWAY as single switch, rather than an AWAY switch inside every HomeKit Accessory.

### ISSUE THREAD

**Issue by leoneleone** [chrisjshull/homebridge-nest#64] opened 2018-08-21 09:48 UTC
@chrisjshull 

**Is your feature request related to a problem? Please describe.**

Yes. Nest AWAY status doesn't work consistently. Most of the time I have to toggle the Away switch twice to get my Nest Cams to 'turn off' correctly according to the AWAY assist rules set up in the Nest app. I believe this may have something to do with the Characteristic.Away that is created by this plugin under every Nest Cam (HomeKit Accessory).

**Describe the solution you'd like**

It would make more sense to consolidate the Nest AWAY status/control under ONE HomeKit Switch Accessory which tied into the one Nest.structure rather than each Nest.camera. 

**Describe alternatives you've considered**

1. "Service.OccupancySensor" could be created instead (of Characteristic.Away for every HomeKit Accessory) to represent the Nest.structure AWAY status, with an added Switch/Toggle to control the AWAY status (which like the current Characteristic.Away in the plugin, this switch would not be visible in the native Home.app tile/Accessory, but can be accessed through third party HomeKit apps like Eve.app).

**Additional context**

Limit Nest Away Switch to inside 1x HomeKit Occupancy Sensor with three Characteristics:
1.  this.addCharacteristic(Characteristic.OccupancyDetected);
2.*** this.addCharacteristic(Characteristic.SecuritySystemCurrentState);
3.*** this.addCharacteristic(Characteristic.SecuritySystemTargetState);

```
/**
 * Service "Occupancy Sensor"
 */

Service.OccupancySensor = function(displayName, subtype) {
  Service.call(this, displayName, '00000086-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.OccupancyDetected);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.StatusActive);
  this.addOptionalCharacteristic(Characteristic.StatusFault);
  this.addOptionalCharacteristic(Characteristic.StatusTampered);
  this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
  this.addOptionalCharacteristic(Characteristic.Name);
};

inherits(Service.OccupancySensor, Service);

Service.OccupancySensor.UUID = '00000086-0000-1000-8000-0026BB765291';


/**
 * Characteristic "Occupancy Detected"
 */

Characteristic.OccupancyDetected = function() {
  Characteristic.call(this, 'Occupancy Detected', '00000071-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 1,
    minValue: 0,
    validValues: [0,1],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.OccupancyDetected, Characteristic);

Characteristic.OccupancyDetected.UUID = '00000071-0000-1000-8000-0026BB765291';

// The value property of OccupancyDetected must be one of the following:
Characteristic.OccupancyDetected.OCCUPANCY_NOT_DETECTED = 0;
Characteristic.OccupancyDetected.OCCUPANCY_DETECTED = 1;

/**
 * Characteristic "Security System Current State"
 */

Characteristic.SecuritySystemCurrentState = function() {
  Characteristic.call(this, 'Security System Current State', '00000066-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 4,
    minValue: 0,
    validValues: [0,1,2,3,4],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.SecuritySystemCurrentState, Characteristic);

Characteristic.SecuritySystemCurrentState.UUID = '00000066-0000-1000-8000-0026BB765291';

// The value property of SecuritySystemCurrentState must be one of the following:
Characteristic.SecuritySystemCurrentState.STAY_ARM = 0;
Characteristic.SecuritySystemCurrentState.AWAY_ARM = 1;
Characteristic.SecuritySystemCurrentState.NIGHT_ARM = 2;
Characteristic.SecuritySystemCurrentState.DISARMED = 3;
Characteristic.SecuritySystemCurrentState.ALARM_TRIGGERED = 4;

/**
 * Characteristic "Security System Target State"
 */

Characteristic.SecuritySystemTargetState = function() {
  Characteristic.call(this, 'Security System Target State', '00000067-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 3,
    minValue: 0,
    validValues: [0,1,2,3],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.SecuritySystemTargetState, Characteristic);

Characteristic.SecuritySystemTargetState.UUID = '00000067-0000-1000-8000-0026BB765291';

// The value property of SecuritySystemTargetState must be one of the following:
Characteristic.SecuritySystemTargetState.STAY_ARM = 0;
Characteristic.SecuritySystemTargetState.AWAY_ARM = 1;
Characteristic.SecuritySystemTargetState.NIGHT_ARM = 2;
Characteristic.SecuritySystemTargetState.DISARM = 3;

```

**Comment by leoneleone** [comment] 2018-08-28 09:15
@chrisjshull 
Any thoughts on this approach?

**Comment by chrisjshull** [comment] 2018-08-30 01:53
I totally agree that home/away state should be per-structure, not per-device. Would love to see a PR opened to make this happen. 😀 

~Chris

**Comment by adriancable** [comment] 2019-07-27 06:31
Duplicate of #103, now fixed in latest commit.

**Closed by adriancable** 2019-07-27 06:31 UTC
