### ISSUE TITLE
Installing this plugin causes fatal error on my raspberry pi until I uninstall the plugin.

### ISSUE THREAD

**Issue by jdgorelick** [chrisjshull/homebridge-nest#471] opened 2021-11-23 04:05 UTC
**Describe the bug**

**To Reproduce**
1. Install plugin

**Expected behavior**

Include with your bug report this version info:
```sh
node --17.1.0
homebridge --1.3.8

#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xb49faf58


#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xb51fbf58


#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xb61fdf58


#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xbeee15e8


#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xb59fcf58
```

**Comment by athal7** [comment] 2021-12-10 18:30
Related https://github.com/homebridge/homebridge/issues/3002#issuecomment-990764077

**Comment by n-mcnulty** [comment] 2021-12-29 21:53
> Related [homebridge/homebridge#3002 (comment)](https://github.com/homebridge/homebridge/issues/3002#issuecomment-990764077)

Just a quick point any odd numbered node release is not officially supported although it may work fine for you it’s not recommended. 

The 3002 issue is unrelated, I can confirm that issue was related to a crash during the install of node 16. When I install node 16 (with nest plugin installed or not) it no longer fails; whereas it used to.

However, I have no problem with node 14. Homebridge-nest works exactly as planned. It is linked to any version of node above 16. 

I have tried uninstalling nest plugin and homebridge works fine (on node 16.13.1) but as soon as I reinstall homebridge-nest; error comes back.

![A88E9AF1-E80D-4915-9E86-E4AAAACAE916](https://user-images.githubusercontent.com/65429441/147706034-3f3c8dfe-f4dd-40bb-8208-e390daa8f2ba.jpeg)

**Comment by ITBlandMCT** [comment] 2022-01-18 01:33
Can confirm problem on pi zero W, Liftoff bailout due to Armv6 not supported with homebridge-nest installed, fine without it. :-(

**Comment by adriancable** [comment] 2022-01-18 01:44
This is due to a V8 bug. It’s fixed in V8 and will also be fixed in the next Node release.

Before then either use Node 16.0 or earlier, or run node with the —no-expose-wasm flag.

**Closed by adriancable** 2022-01-18 01:44 UTC

**Comment by ITBlandMCT** [comment] 2022-01-19 19:04
Thanks for the update!
