### ISSUE TITLE
Siri set temperature feedback issue

### ISSUE THREAD

**Issue by stalinCCCP415** [chrisjshull/homebridge-nest#92] opened 2019-04-26 23:55 UTC
When asking siri to change the set temperature, the feedback is in the format of:

"I changed the temperature from [current ambient temperature] to [new set temperature].

it should be:

"I changed the temperature from [current set temperature] to [new set temperature]"

**To Reproduce**
1. Ask siri to set the temperature to any degree

Include with your bug report this version info:

node --version = v10.15.3
homebridge --version = 0.4.49
plugin version = 2.1.4

![image](https://user-images.githubusercontent.com/36210008/56841697-1a4f9a00-6844-11e9-9354-37913ce7e45a.png)

**Comment by stalinCCCP415** [comment] 2019-04-26 23:57
In the picture 71 is the ambient temperature, 60 is the temperature I asked to be set and 66 degrees is what the current set temperature is.

**Comment by adriancable** [comment] 2019-07-19 19:53
Hi - this is easy to fix, but are you sure this isn't the correct behaviour? Can you confirm with a native HomeKit-supported thermostat that the behaviour is as you expect? Let me know and I will fix if needed.

**Comment by adriancable** [comment] 2019-07-23 02:20
Closing for now. Looking at other thermostats this is a characteristic of HomeKit and it works like this by design (Apple's design).

**Closed by adriancable** 2019-07-23 02:20 UTC

**Comment by stalinCCCP415** [comment] 2019-07-23 02:39
Thanks for looking into it!

On Jul 22, 2019, at 7:20 PM, Adrian Cable <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing for now. Looking at other thermostats this is a characteristic of HomeKit and it works like this by design (Apple's design).

**Comment by adriancable** [comment] 2019-07-23 02:40
No problem. For what it's worth, I also think it's a little strange.
