### ISSUE TITLE
Remote Sensors

### ISSUE THREAD

**Issue by CaptBeard** [chrisjshull/homebridge-nest#38] opened 2018-04-17 21:38 UTC
Has any work been done on adding the Nest remote sensors to this home ridge plugin?  I have two sensors and I’m willing to test. Thanks!

**Comment by chrisjshull** [comment] 2018-04-21 22:44
I'm not seeing a way to access this via the API yet: https://developers.nest.com/documentation/cloud/get-started

Let me know if you do?

**Comment by KaidenR** [comment] 2018-04-23 05:47
Looks like a Nest employee posted to their dev forums that they're "still working on releasing this and other features": 
https://nestdevelopers.io/t/temperature-sensor-api/1317

I picked up a sensor this week and have wanted to ask Siri multiple times what the temperature is in the master bedroom. Hurry up Nest devs!

**Comment by AppleTechy** [comment] 2018-04-24 05:11
I mean the plugin still has the old unofficial API implemented so theoretically it would be possible to reverse the calls from the iOS app. All dependent on the old unofficial API supports the new sensor and hasn’t been changed.

**Comment by francisschmaltz** [comment] 2018-10-10 18:20
> I mean the plugin still has the old unofficial API implemented so theoretically it would be possible to reverse the calls from the iOS app.

I did just that and made a separate node app!

Here's a quick node app I made to get the temp and create an endpoint that [homebridge-http-temperature](https://www.npmjs.com/package/homebridge-http-temperature) can use.

https://github.com/francisschmaltz/nest-remote-sensor

**Comment by Areson** [comment] 2019-03-31 20:29
Along the lines of the http request, there is a REST endpoint you can hit in home.nest.com that returns the sensor data. The authentication for it is just and authentication header using basic authentication.

**Comment by djrobx** [comment] 2019-07-19 20:27
Now that we've moved away from the Nest WWN api, it would be great if we can get this working.   I'd love to add some intelligence to the sensor selection in particular, particularly since Nest's built in hard-coded time slots are so inflexible.

**Comment by adriancable** [comment] 2019-07-19 21:06
@djrobx - give me a little more info what you're looking for. I don't have the Nest sensors so it is difficult for me to test. But there are ways I can get the API info I need to implement, for example getting a HAR log of you using the sensors in the Nest web app in your browser.

**Comment by djrobx** [comment] 2019-07-19 23:15
@adriancable Thanks for considering this request! 

Hopefully the interface is pretty simple.    You have (n) number of extra temperature sensors attached to the nest that all will report their current temperature.     I assume these would show up as different HomeKit child devices.     One of them will be selected as the current active sensor when you sign in.   

<img width="630" alt="Screen Shot 2019-07-19 at 3 51 53 PM" src="https://user-images.githubusercontent.com/1526865/61569815-0d56d700-aa3e-11e9-951d-6a90041b5433.png">

You can change the active sensor by selecting a different one.   So there is one "change to this sensor" action you can make against them (maybe "turn on"? ) 

I took a screenshot of what the interface looks like with my 2 attached sensors   In the HAR logs I've changed the active sensor a couple times and back to the main.   And included the HAR log of the sign in process where it is collecting the info to display.    It looks like the remote sensor stuff is called "rcs" by the api.   I haven't done any API hacking like this before so let me know if it doesn't contain the right info.   I've done some work with homebridge-vera though so once it kind of works I can probably help debug and work out remaining issues once you get me started.  

[nest HAR remote sensors.zip](https://github.com/chrisjshull/homebridge-nest/files/3412960/nest.HAR.remote.sensors.zip)

**Comment by adriancable** [comment] 2019-07-19 23:18
Thanks – will try to take a look over the weekend.

 

-Adrian

**Comment by adriancable** [comment] 2019-07-20 18:16
@djrobx - please send me an email at adrian.cable@gmail.com if you're interested in testing provisional remote sensor support. Your HAR file was super helpful - unless I have screwed up there is a good chance it will work, although I don't have any direct way to test.

**Comment by adriancable** [comment] 2019-07-22 05:36
Remote sensors now supported in the latest commit. Please give it a try!

**Comment by CaptBeard** [comment] 2019-07-22 14:05
I updated my Homebridge-nest to the latest commit, here's it running in iOS 13. Works okay but Siri can't reference the sensors individually.
![IMG_2160](https://user-images.githubusercontent.com/25092259/61638800-22af4980-ac68-11e9-8a2f-dbae95916299.PNG)

**Comment by adriancable** [comment] 2019-07-22 15:39
My understanding is that iOS 13 has reorganised how to Home app displays services, so that multiple services under the same accessory are now grouped together. So in iOS 12 you would have separate "tiles" in the Home app for the thermostat, Home/Away switch, fan switch, Eco switch, temperature sensors. In iOS 13 however they are all displayed under the base thermostat and this is what you're seeing here. I believe this is by design and looking at your screenshot, working correctly.

You should - I understand - still be able to use the individual sensors to control Automations. But, I don't have iOS 13 so can't check how this works.

**Comment by adriancable** [comment] 2019-07-22 15:42
Re. Siri referencing the sensors, I assume (hope?) that you can still assign the individual temperature sensors to rooms in iOS 13, through the settings. Then, you can say "Hey Siri, what's the temperature in the Basement" or similar.

**Comment by toshibochan** [comment] 2019-07-22 20:31
I’m still using previews homebridge-nest plugin and iOS 13 and I see completely different interface on home app compared to @CaptBeard interface. 
![DB5C9A9B-722C-4C20-AEF1-AB14949166FA](https://user-images.githubusercontent.com/15816913/61663218-f524c900-ac84-11e9-876d-a708f9ebe73e.jpeg)
![7E31E941-9623-4D57-BFEA-462EBE0DD515](https://user-images.githubusercontent.com/15816913/61663219-f524c900-ac84-11e9-8465-bed91650e257.jpeg)

**Comment by adriancable** [comment] 2019-07-23 02:25
Looks like this all works now. Closing.

**Comment by Hpridham** [comment] 2019-07-23 03:50
> Re. Siri referencing the sensors, I assume (hope?) that you can still assign the individual temperature sensors to rooms in iOS 13, through the settings. Then, you can say "Hey Siri, what's the temperature in the Basement" or similar.

FYI, in iOS 12, it doesn't seem possible to move a single temperature sensor of a parent device to a new room. It moves everything (including other sensors and functions such as fan and eco controls) to that room.

So, now my living room has 5 temperature sensors in it and Siri gives me a temperature range when responding to "what's the temperature in my living room?".

**Comment by adriancable** [comment] 2019-07-23 05:14
Try the latest commit. You should now be able to move the temperature sensors to individual rooms. Let me know if it works for you.

**Comment by Hpridham** [comment] 2019-07-23 12:57
Works great. I can now move all the temperature sensors into different rooms and individually address those rooms with Siri. Thanks!

**Comment by adriancable** [comment] 2019-07-23 13:34
Great! Closing for now.

**Closed by adriancable** 2019-07-23 13:34 UTC
Labels: awaiting-nest-api-support

**Comment by JonDror** [comment] 2020-05-11 13:46
Is there a specific option that I need to enable to be able to pick a sensor?
I am not seeing the sensor unless I use the Thermostat.SeparateBuiltInTemperatureSensor.Enable option.. but then it’s separate.
![DE64B456-0B52-4B5E-A51E-970C40BE9D03](https://user-images.githubusercontent.com/13471655/81568795-e4545980-9363-11ea-9f18-6e9b8c04af34.jpeg)

**Comment by adriancable** [comment] 2020-05-11 16:11
Jonathan – unfortunately HomeKit just doesn’t have the UI to make this possible. You’ll still need to set the temperature sensor schedule in the Nest app, but the plug-in will then respect that.

 

-Adrian

**Comment by JonDror** [comment] 2020-05-11 17:11
Thanks - I deleted my comment after finding this answer in another issue 😄
I am however not seeing the 'Bedroom' sensor at all in Home.app if I remove
the Thermostat.SeparateBuiltInTemperatureSensor.Enable option. Is that
expected?
(I can create a separate issue if needed)

Thanks!
Jonathan

**Comment by djrobx** [comment] 2020-05-11 17:11
What I would do is add the sensors as switches.  Have the active sensor turned on while the others are off.     This would allow you to switch the active sensor.

**Comment by adriancable** [comment] 2020-05-11 17:40
This could work, but we’d need to make sure this manual mechanism didn’t interfere with the schedule-based temperature sensor selection and other things.

 

-Adrian

**Comment by djrobx** [comment] 2020-05-11 20:47
If the switches read Nest's state, it would work just as it does when you change it on the app (and would even reflect it, if you changed it on the app).   Nest overrides your manual selection at every pre-set schedule interval.    

To roll your own schedule if we had switches, the "workaround" is simple despite Nest's behavior - one could just schedule a manual change a few minutes after the Nest interval.

**Comment by AronEAnderson** [comment] 2020-07-01 07:48
@adriancable: Checking in on @djrobx suggestion above, as I see this issue is marked as Closed... is it possible to setup Nest Temp Sensors as Switches, in order to select which sensor’s temperature reading is being used by the Nest Thermostat?  Can we assist with testing?

**Comment by AronEAnderson** [comment] 2020-07-14 15:45
> @adriancable: Checking in on @djrobx suggestion above, as I see this issue is marked as Closed... is it possible to setup Nest Temp Sensors as Switches, in order to select which sensor’s temperature reading is being used by the Nest Thermostat? Can we assist with testing?

@adriancable Just pinging on this again, as this would be a useful feature for me. Has any progress been made on this feature request?

**Comment by brn2prgrm** [comment] 2021-04-21 16:44
I posted a new issue regarding @AronEAnderson's stale question, but I'll bump here in hopes of giving more context to my request.

It would be great if this could be added...thanks for everything that you've done!!!
