### ISSUE TITLE
ECONNRESET & SIGTERM

### ISSUE THREAD

**Issue by Matsuo3rd** [chrisjshull/homebridge-nest#540] opened 2022-05-02 16:45 UTC
**Describe the bug**
Following homebridge-nest update to 4.6.7 (and still 4.6.8) got twice the following error which kills homebridge instance.
I read ECONNRESET is ok to be met in the logs, but the SIGTERM is killing my entire homebridge.
Nest plugin has been running super stable prior 4.6.7 for 3+ years.

```
[02/05/2022, 18:29:34] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
[02/05/2022, 18:29:34] [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
[02/05/2022, 18:29:34] [Nest] ^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in
[02/05/2022, 18:29:34] [Nest] Retrying in 10 seconds.
[02/05/2022, 18:29:34] Got SIGTERM, shutting down Homebridge...
```

Node.js v16.13.2
Homebridge v1.4.1 (HAP v0.10.2)
macOS Catalina

Using former **Nest** authentication / API (not the new Google one).

**Comment by marklrs** [comment] 2022-05-02 17:05
Seeing the same issue also.

**Comment by adriancable** [comment] 2022-05-02 17:13
Hmm - that doesn’t look good! You are right that the ECONNRESET is harmless in itself, but no idea where the SIGTERM is coming from. Can you paste a longer log (starting a few lines before the error)? Thanks!

**Comment by adriancable** [comment] 2022-05-02 20:20
Update: this should be fixed in 4.6.9. Closing for now, but please re-open if you have further issues after updating. Thanks for reporting!

**Closed by adriancable** 2022-05-02 20:20 UTC

**Comment by Matsuo3rd** [comment] 2022-05-03 07:02
OK. Updated to 4.6.9. Will report back. Thanks for your swift support and great contribution to the community!

**Comment by ZXSwire3** [comment] 2022-05-12 00:47
I just updated Node.js to 16.15.0 and I'm getting the SIGTERM issue even when having the most updated version of the plugin.
```
[5/11/2022, 5:27:32 PM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge ECA7) is running on port 52335.

[5/11/2022, 5:35:54 PM] [Homebridge UI] Running Command: npm install --save homebridge-nest@latest
[5/11/2022, 5:36:52 PM] [Homebridge UI] Changes to config.json saved.
[5/11/2022, 5:36:58 PM] [Homebridge UI] Changes to config.json saved.
[5/11/2022, 5:37:22 PM] [Homebridge UI] Changes to config.json saved.
[5/11/2022, 5:37:29 PM] [Homebridge UI] Homebridge restart request received
[5/11/2022, 5:37:29 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[5/11/2022, 5:37:29 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[5/11/2022, 5:37:29 PM] Got SIGTERM, shutting down Homebridge...
[5/11/2022, 5:37:34 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/11/2022, 5:37:39 PM] [HB Supervisor] Restarting Homebridge...
[5/11/2022, 5:37:39 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/11/2022, 5:37:40 PM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 1902
[5/11/2022, 5:37:43 PM] Loaded config.json with 0 accessories and 3 platforms.
[5/11/2022, 5:37:44 PM] Loaded 1 cached accessories from cachedAccessories.
[5/11/2022, 5:37:44 PM] ---
[5/11/2022, 5:37:48 PM] Loaded plugin: homebridge-dummy@0.6.0
[5/11/2022, 5:37:48 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[5/11/2022, 5:37:48 PM] ---
[5/11/2022, 5:37:48 PM] Loaded plugin: homebridge-ecoplug@0.6.0
[5/11/2022, 5:37:48 PM] Registering platform 'homebridge-ecoplug.EcoPlug'
[5/11/2022, 5:37:48 PM] ---


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7edf1fc8
[5/11/2022, 5:37:48 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTRAP
[5/11/2022, 5:37:53 PM] [HB Supervisor] Restarting Homebridge...
[5/11/2022, 5:37:53 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/11/2022, 5:37:54 PM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 1938
[5/11/2022, 5:37:57 PM] Loaded config.json with 0 accessories and 3 platforms.
[5/11/2022, 5:37:58 PM] Loaded 1 cached accessories from cachedAccessories.
[5/11/2022, 5:37:58 PM] ---
[5/11/2022, 5:38:01 PM] Loaded plugin: homebridge-dummy@0.6.0
[5/11/2022, 5:38:01 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[5/11/2022, 5:38:01 PM] ---
[5/11/2022, 5:38:01 PM] Loaded plugin: homebridge-ecoplug@0.6.0
[5/11/2022, 5:38:01 PM] Registering platform 'homebridge-ecoplug.EcoPlug'
[5/11/2022, 5:38:01 PM] ---
```
I'm not sure if it's really the same issue as the one above, but it just hard crashes homebridge when I install it at all. Without the plugin, everything works fine.

**Comment by adriancable** [comment] 2022-05-12 01:01
@ZXSwire3 - not the same issue I'm afraid.

Can you tell me what platform (hardware, OS, etc.) you're running on? The error you're seeing is a hard crash from V8.

**Comment by ZXSwire3** [comment] 2022-05-12 22:44
@adriancable That's strange, I'm running it on a raspberry pi 3+ I believe, but when I'm in the homebridge ui, it says that I'm using Ubuntu Focal Fossa (20.04.4 LTS). I set up homebridge with docker. I know this isn't a problem with your plugin, but do you have any suggestions on what do to?

**Comment by jnubz** [comment] 2022-05-12 23:45
I'm getting econnreset occasionally, but no sigterms running on an RPi 4b 4gb. As far as I can tell, it's stable as long as everything is updated. But I am not running it in a docket container. Just running directly on the RPi.

**Comment by adriancable** [comment] 2022-05-13 19:26
@jnubz - ECONNRESET does not mean anything is wrong.

@ZXSwire3 - my suggestion is you do some Googling. It seems to be specific to Docker and the cause seems to be mismatched library versions. See for example: https://github.com/FlareSolverr/FlareSolverr/issues/258

**Comment by Matsuo3rd** [comment] 2022-05-14 09:28
Reporting that since 4.6.9 issue has never popped up on my end (12 days runway)
