### ISSUE TITLE
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated.

### ISSUE THREAD

**Issue by roe1974** [chrisjshull/homebridge-nest#118] opened 2019-07-30 07:22 UTC
Hi

Each time i perform an update i get the following error in the console:

npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.

Is this normal ?

Richard

**Comment by gladiatormax** [comment] 2019-07-30 12:16
Hi
I have the same problem, is it normal?

Thx

**Comment by adriancable** [comment] 2019-07-30 14:47
@roe1974 - it is normal and you can ignore it. It is caused by an old library I am using (prompt-promise) which hasn't been updated for a few years. In the next release I will replace the library with a newer equivalent to avoid the message.

**Comment by adriancable** [comment] 2019-07-30 14:55
Fixed in 3.2.2. Will publish to npmjs later today.

**Closed by adriancable** 2019-07-30 14:55 UTC
