### ISSUE TITLE
Group Occupancy Motion Detector and Switch with the Thermostat

### ISSUE THREAD

**Issue by sachangregory** [chrisjshull/homebridge-nest#122] opened 2019-08-01 23:14 UTC
Earlier on 3.1 the Occupancy was grouped with the Thermostat but now it is separate on 3.2.2

I'm on iOS 13 Beta 5 on all my devices and tvOS 13 Beta 5

**Comment by adriancable** [comment] 2019-08-01 23:44
This is by design. Occupancy is related to the structure (i.e. the HomeKit Home) not individual thermostats and so there should be only one per home. It is separated from the thermostat since the thermostat may be in a specific room (or multiple thermostats in different rooms) whereas the occupancy relates to the whole home. Closing for now.

**Closed by adriancable** 2019-08-01 23:44 UTC

**Comment by sachangregory** [comment] 2019-08-02 01:44
Alright! I was wondering why they got separated
