### ISSUE TITLE
Hot water control no longer works, only sets to 30 mins

### ISSUE THREAD

**Issue by j88nyr** [chrisjshull/homebridge-nest#501] opened 2022-01-30 09:51 UTC
**Describe the bug**
Had hot water boost set to 2hrs, but now Nest only boosts for 30 mins

Current config:
    },
    "options": [
        "HomeAway.Disable",
        "Thermostat.Eco.Disable",
        "hotWaterDurationMinutes: 120"
    ],
    "platform": "Nest"

Include with your bug report this version info:
Node.js v16.13.2
NPM v8.1.2
Homebridge 1.4.0
homebridge-nest v4.6.4

When controlling hot water, the logs only show it turning it on or off:
[1/30/2022, 9:51:28 AM] [Nest] Setting hot water state for Downstairs Thermostat to: false
[1/30/2022, 9:51:31 AM] [Nest] Setting hot water state for Downstairs Thermostat to: true

**Comment by adriancable** [comment] 2022-01-30 15:04
Duplicate of #483. Also, user error and not an issue.

**Closed by adriancable** 2022-01-30 15:04 UTC
