### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::57022 only when running as child bridge

### ISSUE THREAD

**Issue by JeffroDB** [chrisjshull/homebridge-nest#449] opened 2021-10-14 13:13 UTC
Receiving the error noted in the log entries below **ONLY** when plugin is running as a child bridge.

Node.js Version is v14.18.0
Homebridge version is 1.3.5

LOG:

[10/14/2021, 9:01:15 AM] [Nest] Launched child bridge with PID 5041
[10/14/2021, 9:01:15 AM] Registering platform 'homebridge-nest.Nest'
[10/14/2021, 9:01:15 AM] [Nest] Loaded homebridge-nest v4.6.2 child bridge successfully
[10/14/2021, 9:01:15 AM] Loaded 2 cached accessories from cachedAccessories.0EBD6C87F395.
Preparing Advertiser for 'Nest 2EDE' using ciao backend!
[10/14/2021, 9:01:15 AM] [Nest] Fetching Nest devices.
Error: listen EADDRINUSE: address already in use :::57022
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1233:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:213:17)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:172:24)

**Comment by adriancable** [comment] 2021-10-15 03:39
@JeffroDB - can you share your config.json? Feel free to black out tokens etc. but don't change the structure.

This error is happening inside Homebridge (not our plug-in).

**Comment by adriancable** [comment] 2021-10-15 22:09
@JeffroDB - I would like you to send the config.json that causes the error you are reporting. If you only get the error in child mode, please send the config.json showing how you’re setting it up in child mode.

**Comment by adriancable** [comment] 2021-10-16 19:40
@JeffroDB - thanks for the updated config - it looks fine.

I think my next suggestion is for you to repost this issue in the Homebridge github issues (not homebridge-nest). I don't think your issue has anything to do with homebridge-nest (or any other specific plug-in). The error you are seeing is coming from Homebridge itself, when it's publishing the bridge, which isn't something that individual plug-ins can influence. Normally Homebridge only does this once, on start up, but it would need to re-publish if your IP address changes which should be unusual but can happen e.g. if your router restarts, or your DHCP lease expires and for whatever reason, the router decides not to keep the original IP. This is a corner case and it's possible this wasn't fully tested with Homebridge for child bridges. Since this is not happening at start-up, this is my best guess at what is happening but to be honest I am not an expert on Homebridge's internal workings.

I note from your config that homebridge-nest is the only child bridge you're using. This is also consistent with my conclusion that the issue being to do with child bridges, rather than homebridge-nest. You would probably find that if you set another one of your plug-ins to be a child bridge (instead of homebridge-nest), you would have the same issue.

Sorry I don't think I can help any further, but hopefully the above gives some useful pointers on things for you to try next.

**Comment by JeffroDB** [comment] 2021-10-16 20:13
Thank you for your thoughtful, clear and consise analysis! Before I post to homebridge github I’ll remove that hard port and give the child bridge another whirl. Would you like me to keep you posted of my results?

**Comment by JeffroDB** [comment] 2021-10-16 21:11
Whoa!

I removed the hard port number from config.jason and it looks like it chose 51070

I left your Nest plugin as non-child and restarted Homebridge.

Things went **wonky** fast. From my log:

Starting to advertise 'Homebridge MacMini 95E1' using ciao backend!
[10/16/2021, 4:20:42 PM] Homebridge v1.3.5 (Homebridge MacMini) is running on port 51070.
[10/16/2021, 4:20:43 PM] [EufySecurity] Restoring existing accessory from cache: eufy HomeBase2
[10/16/2021, 4:20:46 PM] [Nest] initing thermostat (P) "Hallway Thermostat": deviceId: 6416660000C31396 structureId: 6eb085a2-2462-11ec-afdf-126a4f95d85c
[10/16/2021, 4:20:46 PM] [Nest] initing temp_sensor (P) "Living Room": deviceId: 18B430C50A8970EE structureId: 6eb085a2-2462-11ec-afdf-126a4f95d85c
[10/16/2021, 4:46:32 PM] [EufySecurity] Push Closed!
[10/16/2021, 4:46:46 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: ENOTFOUND
[10/16/2021, 4:46:46 PM] [Nest] Retrying in 10 seconds.
[10/16/2021, 4:47:16 PM] [Nest] API observe: error Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND grpc-web.production.nest.com)
    at new NodeError (internal/errors.js:322:7)
    at closeSession (internal/http2/core.js:1110:20)
    at ClientHttp2Session.destroy (internal/http2/core.js:1484:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2916:13)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  cause: Error: getaddrinfo ENOTFOUND grpc-web.production.nest.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'grpc-web.production.nest.com'
  },
  code: 'ERR_HTTP2_STREAM_CANCEL'
}
[10/16/2021, 4:47:16 PM] [Nest] Retrying in 10 seconds.

I'll put the hard port back in config.jason and leave your Nest plugin running non-child. My wife's about to kill me. :-)

Thanks for the time you put into this on your weekend.

**Comment by Marvive** [comment] 2021-11-02 02:43
Came to say I was having the same issue. I'm not totally convinced its a DNS issue for me as removing homebridge-nest fixed the issue of my homebridge crashing frequently.

**Comment by adriancable** [comment] 2021-11-02 02:48
@Marvive - which issue are you having? The OP's original issue ('address already in use'), or their later issue (ENOTFOUND)?

ENOTFOUND is a DNS issue. It can only mean that. There are no other causes. See: https://nodejs.org/api/errors.html

**Comment by Marvive** [comment] 2021-11-02 05:06
Very sorry, I misread things too quickly. I'm having an entirely different issue. I'll try and reach out when I get some time.

**Comment by adriancable** [comment] 2021-11-08 01:45
Going to close this one now. The original issue was likely caused by hard-coding the port. Subsequent posts in this thread relate to different issues that aren't related to the plug-in. @JeffroDB feel free to open a new (clean) issue if you continue to have problems.

**Closed by adriancable** 2021-11-08 01:45 UTC
